import { NestFactory } from '@nestjs/core';
import { AppModule } from '../app.module';
import { Model } from 'mongoose';
import { TestCatalog } from './schemas/test-catalog.schema';

async function seedTestCatalog() {
  const app = await NestFactory.createApplicationContext(AppModule);
  const testCatalogModel = app.get<Model<TestCatalog>>('TestCatalogModel');

  console.log('Starting comprehensive test catalog seeding with age/gender-specific ranges...');

  // Clear existing test catalog
  await testCatalogModel.deleteMany({});
  console.log('Cleared existing test catalog');

  const tests = [
    // ==================== HAEMATOLOGY (ZYBIO ZS-2) ====================
    {
      code: 'HB',
      name: 'Hemoglobin',
      category: 'hematology',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: false,
      description: 'Hemoglobin concentration measurement',
      unit: 'g/dL',
      referenceRanges: [
        { ageGroup: 'Neonatal (0-7 days)',  ageMin: 0,    ageMax: 0.02, gender: 'all', range: '17.0-20.0', unit: 'g/dL', criticalLow: '7.0', criticalHigh: '24.0' },
        { ageGroup: 'Pediatric (7d-13yr)', ageMin: 0.02, ageMax: 13,   gender: 'all', range: '12.0-16.0', unit: 'g/dL', criticalLow: '7.0', criticalHigh: '20.0' },
        { ageGroup: 'Adult Female',         ageMin: 13,                  gender: 'F',   range: '11.5-15.0', unit: 'g/dL', criticalLow: '7.0', criticalHigh: '20.0' },
        { ageGroup: 'Adult Male',           ageMin: 13,                  gender: 'M',   range: '13.5-17.5', unit: 'g/dL', criticalLow: '7.0', criticalHigh: '20.0' },
      ],
    },
    {
      code: 'HCT',
      name: 'Hematocrit',
      category: 'hematology',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: false,
      description: 'Packed cell volume',
      unit: '%',
      referenceRanges: [
        { ageGroup: 'Neonatal (0-7 days)',  ageMin: 0,    ageMax: 0.02, gender: 'all', range: '38.0-68.0', unit: '%', criticalLow: '20', criticalHigh: '70' },
        { ageGroup: 'Pediatric (7d-13yr)', ageMin: 0.02, ageMax: 13,   gender: 'all', range: '35.0-49.0', unit: '%', criticalLow: '20', criticalHigh: '60' },
        { ageGroup: 'Adult Female',         ageMin: 13,                  gender: 'F',   range: '35.0-45.0', unit: '%', criticalLow: '20', criticalHigh: '60' },
        { ageGroup: 'Adult Male',           ageMin: 13,                  gender: 'M',   range: '40.0-54.0', unit: '%', criticalLow: '20', criticalHigh: '60' },
      ],
    },
    {
      code: 'RBC',
      name: 'Red Blood Cell Count',
      category: 'hematology',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: false,
      unit: 'x10¹²/L',
      referenceRanges: [
        { ageGroup: 'Neonatal (0-7 days)',  ageMin: 0,    ageMax: 0.02, gender: 'all', range: '3.50-7.00', unit: 'x10¹²/L' },
        { ageGroup: 'Pediatric (7d-13yr)', ageMin: 0.02, ageMax: 13,   gender: 'all', range: '3.50-5.20', unit: 'x10¹²/L' },
        { ageGroup: 'Adult Female',         ageMin: 13,                  gender: 'F',   range: '3.80-5.10', unit: 'x10¹²/L' },
        { ageGroup: 'Adult Male',           ageMin: 13,                  gender: 'M',   range: '4.50-5.90', unit: 'x10¹²/L' },
      ],
    },
    {
      code: 'WBC',
      name: 'White Blood Cell Count',
      category: 'hematology',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: false,
      unit: 'x10⁹/L',
      referenceRanges: [
        { ageGroup: 'Neonatal (0-7 days)',  ageMin: 0,    ageMax: 0.02, gender: 'all', range: '4.00-20.00', unit: 'x10⁹/L', criticalLow: '2.0', criticalHigh: '30.0' },
        { ageGroup: 'Pediatric (7d-13yr)', ageMin: 0.02, ageMax: 13,   gender: 'all', range: '4.00-12.00', unit: 'x10⁹/L', criticalLow: '2.0', criticalHigh: '30.0' },
        { ageGroup: 'Adult Female',         ageMin: 13,                  gender: 'F',   range: '3.50-9.50',  unit: 'x10⁹/L', criticalLow: '2.0', criticalHigh: '30.0' },
        { ageGroup: 'Adult Male',           ageMin: 13,                  gender: 'M',   range: '4.00-11.00', unit: 'x10⁹/L', criticalLow: '2.0', criticalHigh: '30.0' },
      ],
    },
    {
      code: 'PLT',
      name: 'Platelet Count',
      category: 'hematology',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: false,
      unit: 'x10⁹/L',
      referenceRanges: [
        { ageGroup: 'Neonatal (0-7 days)',  ageMin: 0,    ageMax: 0.02, gender: 'all', range: '100-300', unit: 'x10⁹/L', criticalLow: '50', criticalHigh: '1000' },
        { ageGroup: 'Pediatric (7d-13yr)', ageMin: 0.02, ageMax: 13,   gender: 'all', range: '100-300', unit: 'x10⁹/L', criticalLow: '50', criticalHigh: '1000' },
        { ageGroup: 'Adult',               ageMin: 13,                  gender: 'all', range: '125-350', unit: 'x10⁹/L', criticalLow: '50', criticalHigh: '1000' },
      ],
    },
    {
      code: 'MCV',
      name: 'Mean Corpuscular Volume',
      category: 'hematology',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: false,
      unit: 'fL',
      referenceRanges: [
        { ageGroup: 'Neonatal (0-7 days)',  ageMin: 0,    ageMax: 0.02, gender: 'all', range: '95.0-125.0', unit: 'fL' },
        { ageGroup: 'Pediatric (7d-13yr)', ageMin: 0.02, ageMax: 13,   gender: 'all', range: '80.0-100.0', unit: 'fL' },
        { ageGroup: 'Adult',               ageMin: 13,                  gender: 'all', range: '82.0-100.0', unit: 'fL' },
      ],
    },
    {
      code: 'MCH',
      name: 'Mean Corpuscular Hemoglobin',
      category: 'hematology',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: false,
      unit: 'pg',
      referenceRanges: [
        { ageGroup: 'Neonatal (0-7 days)',  ageMin: 0,    ageMax: 0.02, gender: 'all', range: '30.0-42.0', unit: 'pg' },
        { ageGroup: 'Pediatric (7d-13yr)', ageMin: 0.02, ageMax: 13,   gender: 'all', range: '27.0-34.0', unit: 'pg' },
        { ageGroup: 'Adult',               ageMin: 13,                  gender: 'all', range: '27.0-34.0', unit: 'pg' },
      ],
    },
    {
      code: 'MCHC',
      name: 'Mean Corpuscular Hemoglobin Concentration',
      category: 'hematology',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: false,
      unit: 'g/dL',
      referenceRanges: [
        { ageGroup: 'Neonatal (0-7 days)',  ageMin: 0,    ageMax: 0.02, gender: 'all', range: '30-34', unit: 'g/dL' },
        { ageGroup: 'Pediatric (7d-13yr)', ageMin: 0.02, ageMax: 13,   gender: 'all', range: '31-37', unit: 'g/dL' },
        { ageGroup: 'Adult',               ageMin: 13,                  gender: 'all', range: '31.6-35.4', unit: 'g/dL' },
      ],
    },
    {
      code: 'RDW',
      name: 'Red Cell Distribution Width',
      category: 'hematology',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: false,
      unit: '%',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '11.5-14.5', unit: '%' },
      ],
    },
    {
      code: 'RDWCV',
      name: 'Red Cell Distribution Width - CV',
      category: 'hematology',
      price: 0,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: '%',
      description: 'Analyzer-derived erythrocyte anisocytosis index (coefficient of variation)',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '11.0-16.0', unit: '%' },
      ],
    },
    {
      code: 'RDWSD',
      name: 'Red Cell Distribution Width - SD',
      category: 'hematology',
      price: 0,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'fL',
      description: 'Analyzer-derived erythrocyte anisocytosis index (standard deviation)',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '35.0-56.0', unit: 'fL' },
      ],
    },
    {
      code: 'MPV',
      name: 'Mean Platelet Volume',
      category: 'hematology',
      price: 0,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'fL',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '6.5-12.0', unit: 'fL' },
      ],
    },
    {
      code: 'PDW',
      name: 'Platelet Distribution Width',
      category: 'hematology',
      price: 0,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'fL',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '9.0-17.0', unit: 'fL' },
      ],
    },
    {
      code: 'PLTCT',
      name: 'Plateletcrit',
      category: 'hematology',
      price: 0,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'ml/L',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '1.08-2.82', unit: 'ml/L' },
      ],
    },
    {
      code: 'PLCR',
      name: 'Platelet Large Cell Ratio',
      category: 'hematology',
      price: 0,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: '%',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '11.0-45.0', unit: '%' },
      ],
    },
    {
      code: 'PLCC',
      name: 'Platelet Large Cell Count',
      category: 'hematology',
      price: 0,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'x10⁹/L',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '30-90', unit: 'x10⁹/L' },
      ],
    },
    {
      code: 'NEUTA',
      name: 'Neutrophils #',
      category: 'hematology',
      price: 0,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'x10⁹/L',
      referenceRanges: [
        { ageGroup: 'Neonatal (0-7 days)',  ageMin: 0,    ageMax: 0.02, gender: 'all', range: '1.60-16.00', unit: 'x10⁹/L', criticalLow: '1.0' },
        { ageGroup: 'Pediatric (7d-13yr)', ageMin: 0.02, ageMax: 13,   gender: 'all', range: '2.00-8.00',  unit: 'x10⁹/L', criticalLow: '1.0' },
        { ageGroup: 'Adult',               ageMin: 13,                  gender: 'all', range: '1.80-6.30',  unit: 'x10⁹/L', criticalLow: '1.0' },
      ],
    },
    {
      code: 'LYMPHA',
      name: 'Lymphocytes #',
      category: 'hematology',
      price: 0,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'x10⁹/L',
      referenceRanges: [
        { ageGroup: 'Neonatal (0-7 days)',  ageMin: 0,    ageMax: 0.02, gender: 'all', range: '0.40-12.00', unit: 'x10⁹/L' },
        { ageGroup: 'Pediatric (7d-13yr)', ageMin: 0.02, ageMax: 13,   gender: 'all', range: '0.80-7.00',  unit: 'x10⁹/L' },
        { ageGroup: 'Adult',               ageMin: 13,                  gender: 'all', range: '1.10-3.20',  unit: 'x10⁹/L' },
      ],
    },
    {
      code: 'MONOA',
      name: 'Monocytes #',
      category: 'hematology',
      price: 0,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'x10⁹/L',
      referenceRanges: [
        { ageGroup: 'Neonatal (0-7 days)',  ageMin: 0,    ageMax: 0.02, gender: 'all', range: '0.12-2.50', unit: 'x10⁹/L' },
        { ageGroup: 'Pediatric (7d-13yr)', ageMin: 0.02, ageMax: 13,   gender: 'all', range: '0.12-1.20', unit: 'x10⁹/L' },
        { ageGroup: 'Adult',               ageMin: 13,                  gender: 'all', range: '0.10-0.60', unit: 'x10⁹/L' },
      ],
    },
    {
      code: 'EOSA',
      name: 'Eosinophils #',
      category: 'hematology',
      price: 0,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'x10⁹/L',
      referenceRanges: [
        { ageGroup: 'Neonatal (0-7 days)',  ageMin: 0,    ageMax: 0.02, gender: 'all', range: '0.02-0.80', unit: 'x10⁹/L' },
        { ageGroup: 'Pediatric (7d-13yr)', ageMin: 0.02, ageMax: 13,   gender: 'all', range: '0.02-0.80', unit: 'x10⁹/L' },
        { ageGroup: 'Adult',               ageMin: 13,                  gender: 'all', range: '0.02-0.52', unit: 'x10⁹/L' },
      ],
    },
    {
      code: 'BASOA',
      name: 'Basophils #',
      category: 'hematology',
      price: 0,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'x10⁹/L',
      referenceRanges: [
        { ageGroup: 'Neonatal (0-7 days)',  ageMin: 0,    ageMax: 0.02, gender: 'all', range: '0.00-0.20', unit: 'x10⁹/L' },
        { ageGroup: 'Pediatric (7d-13yr)', ageMin: 0.02, ageMax: 13,   gender: 'all', range: '0.00-0.10', unit: 'x10⁹/L' },
        { ageGroup: 'Adult',               ageMin: 13,                  gender: 'all', range: '0.00-0.06', unit: 'x10⁹/L' },
      ],
    },
    {
      code: 'NEUT',
      name: 'Neutrophils',
      category: 'hematology',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: false,
      unit: '%',
      referenceRanges: [
        { ageGroup: 'Newborn (0-2 weeks)', ageMin: 0, ageMax: 0.04, gender: 'all', range: '40-80', unit: '%' },
        { ageGroup: '2 weeks - 1 month', ageMin: 0.04, ageMax: 0.08, gender: 'all', range: '30-60', unit: '%' },
        { ageGroup: '1-6 months', ageMin: 0.08, ageMax: 0.5, gender: 'all', range: '20-40', unit: '%' },
        { ageGroup: '6 months - 2 years', ageMin: 0.5, ageMax: 2, gender: 'all', range: '25-45', unit: '%' },
        { ageGroup: '2-6 years', ageMin: 2, ageMax: 6, gender: 'all', range: '30-55', unit: '%' },
        { ageGroup: '6-12 years', ageMin: 6, ageMax: 12, gender: 'all', range: '35-65', unit: '%' },
        { ageGroup: 'Neonatal (0-7 days)',  ageMin: 0,    ageMax: 0.02, gender: 'all', range: '40.0-80.0', unit: '%' },
        { ageGroup: 'Pediatric (7d-13yr)', ageMin: 0.02, ageMax: 13,   gender: 'all', range: '50.0-70.0', unit: '%' },
        { ageGroup: 'Adult',               ageMin: 13,                  gender: 'all', range: '40.0-75.0', unit: '%' },
      ],
    },
    {
      code: 'LYMPH',
      name: 'Lymphocytes',
      category: 'hematology',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: false,
      unit: '%',
      referenceRanges: [
        { ageGroup: 'Newborn (0-2 weeks)', ageMin: 0, ageMax: 0.04, gender: 'all', range: '20-50', unit: '%' },
        { ageGroup: '2 weeks - 1 month', ageMin: 0.04, ageMax: 0.08, gender: 'all', range: '35-65', unit: '%' },
        { ageGroup: '1-6 months', ageMin: 0.08, ageMax: 0.5, gender: 'all', range: '50-70', unit: '%' },
        { ageGroup: '6 months - 2 years', ageMin: 0.5, ageMax: 2, gender: 'all', range: '45-75', unit: '%' },
        { ageGroup: '2-6 years', ageMin: 2, ageMax: 6, gender: 'all', range: '35-60', unit: '%' },
        { ageGroup: '6-12 years', ageMin: 6, ageMax: 12, gender: 'all', range: '25-50', unit: '%' },
        { ageGroup: 'Neonatal (0-7 days)',  ageMin: 0,    ageMax: 0.02, gender: 'all', range: '10.0-60.0', unit: '%' },
        { ageGroup: 'Pediatric (7d-13yr)', ageMin: 0.02, ageMax: 13,   gender: 'all', range: '20.0-60.0', unit: '%' },
        { ageGroup: 'Adult',               ageMin: 13,                  gender: 'all', range: '20.0-50.0', unit: '%' },
      ],
    },
    {
      code: 'MONO',
      name: 'Monocytes',
      category: 'hematology',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: false,
      unit: '%',
      referenceRanges: [
        { ageGroup: 'Newborn (0-2 weeks)', ageMin: 0, ageMax: 0.04, gender: 'all', range: '3-10', unit: '%' },
        { ageGroup: '2 weeks - 1 month', ageMin: 0.04, ageMax: 0.08, gender: 'all', range: '3-10', unit: '%' },
        { ageGroup: '1-6 months', ageMin: 0.08, ageMax: 0.5, gender: 'all', range: '3-10', unit: '%' },
        { ageGroup: '6 months - 2 years', ageMin: 0.5, ageMax: 2, gender: 'all', range: '3-10', unit: '%' },
        { ageGroup: '2-6 years', ageMin: 2, ageMax: 6, gender: 'all', range: '2-10', unit: '%' },
        { ageGroup: '6-12 years', ageMin: 6, ageMax: 12, gender: 'all', range: '2-10', unit: '%' },
        { ageGroup: 'Neonatal (0-7 days)',  ageMin: 0,    ageMax: 0.02, gender: 'all', range: '3.0-13.0', unit: '%' },
        { ageGroup: 'Pediatric (7d-13yr)', ageMin: 0.02, ageMax: 13,   gender: 'all', range: '3.0-12.0', unit: '%' },
        { ageGroup: 'Adult',               ageMin: 13,                  gender: 'all', range: '3.0-10.0', unit: '%' },
      ],
    },
    {
      code: 'EOS',
      name: 'Eosinophils',
      category: 'hematology',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: false,
      unit: '%',
      referenceRanges: [
        { ageGroup: 'Newborn (0-2 weeks)', ageMin: 0, ageMax: 0.04, gender: 'all', range: '0-4', unit: '%' },
        { ageGroup: '2 weeks - 1 month', ageMin: 0.04, ageMax: 0.08, gender: 'all', range: '0-4', unit: '%' },
        { ageGroup: '1-6 months', ageMin: 0.08, ageMax: 0.5, gender: 'all', range: '0-5', unit: '%' },
        { ageGroup: '6 months - 2 years', ageMin: 0.5, ageMax: 2, gender: 'all', range: '0-5', unit: '%' },
        { ageGroup: '2-6 years', ageMin: 2, ageMax: 6, gender: 'all', range: '0-6', unit: '%' },
        { ageGroup: '6-12 years', ageMin: 6, ageMax: 12, gender: 'all', range: '0-6', unit: '%' },
        { ageGroup: 'Neonatal (0-7 days)',  ageMin: 0,    ageMax: 0.02, gender: 'all', range: '0.5-5.0', unit: '%' },
        { ageGroup: 'Pediatric (7d-13yr)', ageMin: 0.02, ageMax: 13,   gender: 'all', range: '0.5-5.0', unit: '%' },
        { ageGroup: 'Adult',               ageMin: 13,                  gender: 'all', range: '0.4-8.0', unit: '%' },
      ],
    },
    {
      code: 'BASO',
      name: 'Basophils',
      category: 'hematology',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: false,
      unit: '%',
      referenceRanges: [
        { ageGroup: 'Newborn (0-2 weeks)', ageMin: 0, ageMax: 0.04, gender: 'all', range: '0-1', unit: '%' },
        { ageGroup: '2 weeks - 1 month', ageMin: 0.04, ageMax: 0.08, gender: 'all', range: '0-1', unit: '%' },
        { ageGroup: '1-6 months', ageMin: 0.08, ageMax: 0.5, gender: 'all', range: '0-1', unit: '%' },
        { ageGroup: '6 months - 2 years', ageMin: 0.5, ageMax: 2, gender: 'all', range: '0-1', unit: '%' },
        { ageGroup: '2-6 years', ageMin: 2, ageMax: 6, gender: 'all', range: '0-1', unit: '%' },
        { ageGroup: '6-12 years', ageMin: 6, ageMax: 12, gender: 'all', range: '0-1', unit: '%' },
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '0.0-1.0', unit: '%' },
      ],
    },
    {
      code: 'ESR',
      name: 'Erythrocyte Sedimentation Rate',
      category: 'hematology',
      price: 80,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mm/hr',
      referenceRanges: [
        { ageGroup: 'Newborn', ageMin: 0, ageMax: 0.04, gender: 'all', range: '0-2', unit: 'mm/hr' },
        { ageGroup: 'Child', ageMin: 0.04, ageMax: 18, gender: 'all', range: '0-10', unit: 'mm/hr' },
        { ageGroup: 'Adult Male', ageMin: 18, ageMax: 50, gender: 'M', range: '0-15', unit: 'mm/hr' },
        { ageGroup: 'Adult Female', ageMin: 18, ageMax: 50, gender: 'F', range: '0-20', unit: 'mm/hr' },
        { ageGroup: 'Elderly Male', ageMin: 50, gender: 'M', range: '0-20', unit: 'mm/hr' },
        { ageGroup: 'Elderly Female', ageMin: 50, gender: 'F', range: '0-30', unit: 'mm/hr' },
      ],
    },
    {
      code: 'FBC',
      name: 'Full Blood Count',
      category: 'hematology',
      price: 150,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      description: 'Complete blood count with differential',
    },

    // ==================== CLINICAL CHEMISTRY (ZYBIO EXC-200) ====================
    {
      code: 'ALT',
      name: 'Alanine Aminotransferase',
      category: 'chemistry',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'U/L',
      referenceRanges: [
        { ageGroup: 'Adult Male', ageMin: 18, ageMax: 65, gender: 'M', range: '7-56', unit: 'U/L' },
        { ageGroup: 'Adult Female', ageMin: 18, ageMax: 65, gender: 'F', range: '7-45', unit: 'U/L' },
        { ageGroup: 'Elderly', ageMin: 65, gender: 'all', range: '7-50', unit: 'U/L' },
      ],
    },
    {
      code: 'AST',
      name: 'Aspartate Aminotransferase',
      category: 'chemistry',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'U/L',
      referenceRanges: [
        { ageGroup: 'Adult Male', ageMin: 18, ageMax: 65, gender: 'M', range: '10-40', unit: 'U/L' },
        { ageGroup: 'Adult Female', ageMin: 18, ageMax: 65, gender: 'F', range: '10-35', unit: 'U/L' },
        { ageGroup: 'Elderly', ageMin: 65, gender: 'all', range: '10-40', unit: 'U/L' },
      ],
    },
    {
      code: 'ALP',
      name: 'Alkaline Phosphatase',
      category: 'chemistry',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'U/L',
      referenceRanges: [
        { ageGroup: 'Newborn', ageMin: 0, ageMax: 0.08, gender: 'all', range: '75-400', unit: 'U/L' },
        { ageGroup: '1 month - 1 year', ageMin: 0.08, ageMax: 1, gender: 'all', range: '82-383', unit: 'U/L' },
        { ageGroup: '1-3 years', ageMin: 1, ageMax: 3, gender: 'all', range: '104-345', unit: 'U/L' },
        { ageGroup: '4-6 years', ageMin: 4, ageMax: 6, gender: 'all', range: '93-309', unit: 'U/L' },
        { ageGroup: '7-9 years', ageMin: 7, ageMax: 9, gender: 'all', range: '69-325', unit: 'U/L' },
        { ageGroup: '10-12 years', ageMin: 10, ageMax: 12, gender: 'all', range: '42-362', unit: 'U/L' },
        { ageGroup: '13-15 years', ageMin: 13, ageMax: 15, gender: 'M', range: '74-390', unit: 'U/L' },
        { ageGroup: '13-15 years', ageMin: 13, ageMax: 15, gender: 'F', range: '50-162', unit: 'U/L' },
        { ageGroup: '16-18 years', ageMin: 16, ageMax: 18, gender: 'M', range: '52-171', unit: 'U/L' },
        { ageGroup: '16-18 years', ageMin: 16, ageMax: 18, gender: 'F', range: '47-119', unit: 'U/L' },
        { ageGroup: 'Adult', ageMin: 18, ageMax: 65, gender: 'all', range: '44-147', unit: 'U/L' },
        { ageGroup: 'Elderly', ageMin: 65, gender: 'all', range: '44-147', unit: 'U/L' },
      ],
    },
    {
      code: 'GGT',
      name: 'Gamma-Glutamyl Transferase',
      category: 'chemistry',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'U/L',
      referenceRanges: [
        { ageGroup: 'Adult Male', ageMin: 18, gender: 'M', range: '8-61', unit: 'U/L' },
        { ageGroup: 'Adult Female', ageMin: 18, gender: 'F', range: '5-36', unit: 'U/L' },
      ],
    },
    {
      code: 'TBIL',
      name: 'Total Bilirubin',
      category: 'chemistry',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mg/dL',
      referenceRanges: [
        { ageGroup: 'Newborn (0-24 hours)', ageMin: 0, ageMax: 0.003, gender: 'all', range: '1.0-12.0', unit: 'mg/dL', criticalHigh: '15.0' },
        { ageGroup: 'Newborn (3-5 days)', ageMin: 0.008, ageMax: 0.014, gender: 'all', range: '1.5-12.0', unit: 'mg/dL', criticalHigh: '15.0' },
        { ageGroup: 'Child (6 days - 18 years)', ageMin: 0.016, ageMax: 18, gender: 'all', range: '0.3-1.2', unit: 'mg/dL' },
        { ageGroup: 'Adult', ageMin: 18, gender: 'all', range: '0.3-1.2', unit: 'mg/dL', criticalHigh: '15.0' },
      ],
    },
    {
      code: 'DBIL',
      name: 'Direct Bilirubin',
      category: 'chemistry',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mg/dL',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '0.0-0.3', unit: 'mg/dL' },
      ],
    },
    {
      code: 'IBIL',
      name: 'Indirect Bilirubin',
      category: 'chemistry',
      price: 0,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: false,
      description: 'Calculated value: Total Bilirubin - Direct Bilirubin',
      unit: 'mg/dL',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '0.2-0.8', unit: 'mg/dL' },
      ],
    },
    {
      code: 'TP',
      name: 'Total Protein',
      category: 'chemistry',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'g/dL',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '6.0-8.3', unit: 'g/dL' },
      ],
    },
    {
      code: 'ALB',
      name: 'Albumin',
      category: 'chemistry',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'g/dL',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '3.5-5.5', unit: 'g/dL' },
      ],
    },
    {
      code: 'GLOB',
      name: 'Globulin',
      category: 'chemistry',
      price: 0,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: false,
      description: 'Calculated value: Total Protein - Albumin',
      unit: 'g/dL',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '2.0-3.5', unit: 'g/dL' },
      ],
    },
    {
      code: 'CREAT',
      name: 'Creatinine',
      category: 'chemistry',
      price: 90,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mg/dL',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '0.4-1.10', unit: 'mg/dL', criticalHigh: '5.0' },
      ],
    },
    {
      code: 'UREA',
      name: 'Urea',
      category: 'chemistry',
      price: 80,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mg/dL',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '10.2-49.8', unit: 'mg/dL' },
      ],
    },
    {
      code: 'UA',
      name: 'Uric Acid',
      category: 'chemistry',
      price: 80,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mg/dL',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '2.35-7.0', unit: 'mg/dL' },
      ],
    },
    {
      code: 'CHOL',
      name: 'Total Cholesterol',
      category: 'chemistry',
      price: 80,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mg/dL',
      referenceRanges: [
        { ageGroup: 'Desirable', ageMin: 18, gender: 'all', range: '<200', unit: 'mg/dL' },
        { ageGroup: 'Borderline High', ageMin: 18, gender: 'all', range: '200-239', unit: 'mg/dL' },
        { ageGroup: 'High', ageMin: 18, gender: 'all', range: '≥240', unit: 'mg/dL' },
      ],
    },
    {
      code: 'TG',
      name: 'Triglycerides',
      category: 'chemistry',
      price: 80,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mg/dL',
      referenceRanges: [
        { ageGroup: 'Adult', ageMin: 18, gender: 'all', range: '0-204', unit: 'mg/dL', criticalHigh: '500' },
      ],
    },
    {
      code: 'HDL',
      name: 'HDL Cholesterol',
      category: 'chemistry',
      price: 120,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mg/dL',
      referenceRanges: [
        { ageGroup: 'Male (Optimal)', ageMin: 18, gender: 'M', range: '>40', unit: 'mg/dL' },
        { ageGroup: 'Female (Optimal)', ageMin: 18, gender: 'F', range: '>50', unit: 'mg/dL' },
      ],
    },
    {
      code: 'LDL',
      name: 'LDL Cholesterol',
      category: 'chemistry',
      price: 150,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mg/dL',
      referenceRanges: [
        { ageGroup: 'Optimal', ageMin: 18, gender: 'all', range: '<100', unit: 'mg/dL' },
        { ageGroup: 'Near Optimal', ageMin: 18, gender: 'all', range: '100-129', unit: 'mg/dL' },
        { ageGroup: 'Borderline High', ageMin: 18, gender: 'all', range: '130-159', unit: 'mg/dL' },
        { ageGroup: 'High', ageMin: 18, gender: 'all', range: '≥160', unit: 'mg/dL' },
      ],
    },
    {
      code: 'VLDL',
      name: 'VLDL Cholesterol',
      category: 'chemistry',
      price: 0,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: false,
      description: 'Calculated value: Triglycerides / 5',
      unit: 'mg/dL',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '<30', unit: 'mg/dL' },
      ],
    },
    {
      code: 'GLU',
      name: 'Fasting Blood Glucose',
      category: 'chemistry',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mmol/L',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 18, gender: 'all', range: '3.5-5.9', unit: 'mmol/L', criticalLow: '2.8', criticalHigh: '27.8' },
        { ageGroup: 'Prediabetes', ageMin: 18, gender: 'all', range: '5.6-6.9', unit: 'mmol/L' },
        { ageGroup: 'Diabetes', ageMin: 18, gender: 'all', range: '≥7.0', unit: 'mmol/L' },
      ],
    },
    {
      code: 'RBS',
      name: 'Random Blood Sugar',
      category: 'chemistry',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'mmol/L',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 18, gender: 'all', range: '<7.8', unit: 'mmol/L', criticalLow: '2.8', criticalHigh: '27.8' },
        { ageGroup: 'Prediabetes', ageMin: 18, gender: 'all', range: '7.8-11.0', unit: 'mmol/L' },
        { ageGroup: 'Diabetes', ageMin: 18, gender: 'all', range: '≥11.1', unit: 'mmol/L' },
      ],
    },
    {
      code: 'HBA1C',
      name: 'Glycated Hemoglobin',
      category: 'immunoassay',
      price: 170,
      sampleType: 'blood',
      turnaroundTime: 180,
      isActive: true,
      unit: '%',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 18, gender: 'all', range: '<5.7', unit: '%' },
        { ageGroup: 'Prediabetes', ageMin: 18, gender: 'all', range: '5.7-6.4', unit: '%' },
        { ageGroup: 'Diabetes', ageMin: 18, gender: 'all', range: '≥6.5', unit: '%' },
      ],
    },
    {
      code: 'LFT',
      name: 'Liver Function Test',
      category: 'chemistry',
      price: 320,
      sampleType: 'blood',
      turnaroundTime: 180,
      isActive: true,
      description: 'Complete liver function panel',
    },
    {
      code: 'RFT',
      name: 'Renal Function Test',
      category: 'chemistry',
      price: 400,
      sampleType: 'blood',
      turnaroundTime: 180,
      isActive: true,
      description: 'Complete kidney function panel',
    },
    {
      code: 'LIPID',
      name: 'Lipid Profile',
      category: 'chemistry',
      price: 320,
      sampleType: 'blood',
      turnaroundTime: 180,
      isActive: true,
      description: 'Complete lipid panel',
    },

    // ==================== ELECTROLYTES (CBS-50) ====================
    {
      code: 'K',
      name: 'Potassium',
      category: 'chemistry',
      price: 35,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mmol/L',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '3.5-5.2', unit: 'mmol/L', criticalLow: '2.5', criticalHigh: '6.5' },
      ],
    },
    {
      code: 'NA',
      name: 'Sodium',
      category: 'chemistry',
      price: 35,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mmol/L',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '136-145', unit: 'mmol/L', criticalLow: '120', criticalHigh: '160' },
      ],
    },
    {
      code: 'CL',
      name: 'Chloride',
      category: 'chemistry',
      price: 35,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mmol/L',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '96-108', unit: 'mmol/L', criticalLow: '80', criticalHigh: '115' },
      ],
    },
    {
      code: 'ICA',
      name: 'Ionized Calcium',
      category: 'chemistry',
      price: 35,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mmol/L',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '1.05-1.35', unit: 'mmol/L', criticalLow: '0.8', criticalHigh: '1.5' },
      ],
    },
    {
      code: 'NCA',
      name: 'Non-ionized Calcium',
      category: 'chemistry',
      price: 35,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mmol/L',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '1.05-1.35', unit: 'mmol/L', criticalLow: '0.8', criticalHigh: '1.5' },
      ],
    },
    {
      code: 'TCA',
      name: 'Total Calcium',
      category: 'chemistry',
      price: 35,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mmol/L',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '2.08-2.60', unit: 'mmol/L', criticalLow: '1.5', criticalHigh: '3.0' },
      ],
    },
    {
      code: 'ELEC',
      name: 'Electrolyte Panel',
      category: 'chemistry',
      price: 210,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      description: 'Complete electrolyte panel - K, Na, Cl, iCa, nCa, TCa',
    },

    // ==================== POCT TESTS (WONDFO FINECARE FIA) ====================
    {
      code: 'CRP',
      name: 'C-Reactive Protein',
      category: 'immunoassay',
      linkedTests: ['HSCRP'],
      price: 190,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'mg/L',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: '0-10.0', unit: 'mg/L' },
      ],
    },
    {
      code: 'HSCRP',
      name: 'hs CRP',
      category: 'immunoassay',
      price: 350,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'mg/L',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: '0-1.0', unit: 'mg/L' },
      ],
    },
    {
      code: 'PCT',
      name: 'Procalcitonin',
      category: 'immunoassay',
      price: 270,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'ng/mL',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: '<0.5', unit: 'ng/mL' },
        { ageGroup: 'Possible Bacterial Infection', ageMin: 0, gender: 'all', range: '0.5-2.0', unit: 'ng/mL' },
        { ageGroup: 'Sepsis Likely', ageMin: 0, gender: 'all', range: '>2.0', unit: 'ng/mL', criticalHigh: '2.0' },
      ],
    },
    {
      code: 'TROP',
      name: 'Troponin I',
      category: 'immunoassay',
      price: 270,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'ng/mL',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: '<0.04', unit: 'ng/mL', criticalHigh: '0.4' },
        { ageGroup: 'Elevated', ageMin: 0, gender: 'all', range: '0.04-0.4', unit: 'ng/mL' },
        { ageGroup: 'MI Likely', ageMin: 0, gender: 'all', range: '>0.4', unit: 'ng/mL' },
      ],
    },
    {
      code: 'BNP',
      name: 'B-Type Natriuretic Peptide',
      category: 'immunoassay',
      price: 370,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'pg/mL',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: '<100', unit: 'pg/mL' },
        { ageGroup: 'Heart Failure Possible', ageMin: 0, gender: 'all', range: '100-400', unit: 'pg/mL' },
        { ageGroup: 'Heart Failure Likely', ageMin: 0, gender: 'all', range: '>400', unit: 'pg/mL', criticalHigh: '400' },
      ],
    },
    {
      code: 'NTPRO',
      name: 'NT-proBNP',
      category: 'immunoassay',
      price: 370,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'pg/mL',
      referenceRanges: [
        { ageGroup: '<50 years', ageMin: 0, ageMax: 50, gender: 'all', range: '<125', unit: 'pg/mL', criticalHigh: '450' },
        { ageGroup: '50-75 years', ageMin: 50, ageMax: 75, gender: 'all', range: '<125', unit: 'pg/mL', criticalHigh: '900' },
        { ageGroup: '>75 years', ageMin: 75, gender: 'all', range: '<125', unit: 'pg/mL', criticalHigh: '1800' },
      ],
    },
    {
      code: 'TSH',
      name: 'Thyroid Stimulating Hormone',
      category: 'immunoassay',
      price: 220,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'µIU/mL',
      referenceRanges: [
        { ageGroup: 'Adult', ageMin: 18, ageMax: 65, gender: 'all', range: '0.5-4.0', unit: 'µIU/mL' },
        { ageGroup: 'Pregnancy (1st trimester)', ageMin: 18, ageMax: 45, gender: 'F', pregnancy: true, condition: '1st trimester', range: '0.1-2.5', unit: 'µIU/mL' },
        { ageGroup: 'Pregnancy (2nd trimester)', ageMin: 18, ageMax: 45, gender: 'F', pregnancy: true, condition: '2nd trimester', range: '0.2-3.0', unit: 'µIU/mL' },
        { ageGroup: 'Pregnancy (3rd trimester)', ageMin: 18, ageMax: 45, gender: 'F', pregnancy: true, condition: '3rd trimester', range: '0.3-3.0', unit: 'µIU/mL' },
      ],
    },
    {
      code: 'FT4',
      name: 'Free T4',
      category: 'immunoassay',
      price: 220,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'ng/dL',
      referenceRanges: [
        { ageGroup: 'Adult', ageMin: 18, gender: 'all', range: '0.8-1.8', unit: 'ng/dL' },
        { ageGroup: 'Pregnancy', ageMin: 18, ageMax: 45, gender: 'F', pregnancy: true, range: '0.8-1.5', unit: 'ng/dL' },
      ],
    },
    {
      code: 'FT3',
      name: 'Free T3',
      category: 'immunoassay',
      price: 220,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'pg/mL',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '2.3-4.2', unit: 'pg/mL' },
      ],
    },
    {
      code: 'AFP',
      name: 'Alpha-Fetoprotein',
      category: 'immunoassay',
      price: 240,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'ng/mL',
      referenceRanges: [
        { ageGroup: 'Adult', ageMin: 18, gender: 'all', range: '<10', unit: 'ng/mL' },
        { ageGroup: 'Pregnancy', ageMin: 18, ageMax: 45, gender: 'F', pregnancy: true, range: 'Elevated (varies by week)', unit: 'ng/mL' },
      ],
    },
    {
      code: 'PSA',
      name: 'Prostate Specific Antigen',
      category: 'immunoassay',
      price: 240,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'ng/mL',
      referenceRanges: [
        { ageGroup: '40-49 years', ageMin: 40, ageMax: 49, gender: 'M', range: '<2.5', unit: 'ng/mL' },
        { ageGroup: '50-59 years', ageMin: 50, ageMax: 59, gender: 'M', range: '<3.5', unit: 'ng/mL' },
        { ageGroup: '60-69 years', ageMin: 60, ageMax: 69, gender: 'M', range: '<4.5', unit: 'ng/mL' },
        { ageGroup: '70-79 years', ageMin: 70, ageMax: 79, gender: 'M', range: '<6.5', unit: 'ng/mL' },
      ],
    },
    {
      code: 'CEA',
      name: 'Carcinoembryonic Antigen',
      category: 'immunoassay',
      price: 240,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'ng/mL',
      referenceRanges: [
        { ageGroup: 'Non-smoker', ageMin: 18, gender: 'all', range: '<3.0', unit: 'ng/mL' },
        { ageGroup: 'Smoker', ageMin: 18, gender: 'all', range: '<5.0', unit: 'ng/mL' },
      ],
    },
    {
      code: 'ESTRADIOL',
      name: 'Estradiol',
      category: 'immunoassay',
      price: 280,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'pg/mL',
      referenceRanges: [
        { ageGroup: 'Female (Follicular)', ageMin: 18, ageMax: 50, gender: 'F', condition: 'Follicular', range: '20-350', unit: 'pg/mL' },
        { ageGroup: 'Female (Ovulation)', ageMin: 18, ageMax: 50, gender: 'F', condition: 'Ovulation', range: '150-750', unit: 'pg/mL' },
        { ageGroup: 'Female (Luteal)', ageMin: 18, ageMax: 50, gender: 'F', condition: 'Luteal', range: '30-450', unit: 'pg/mL' },
        { ageGroup: 'Female (Postmenopause)', ageMin: 50, gender: 'F', condition: 'Postmenopause', range: '<20', unit: 'pg/mL' },
      ],
    },
    {
      code: 'PROG',
      name: 'Progesterone',
      category: 'immunoassay',
      price: 220,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'ng/mL',
      referenceRanges: [
        { ageGroup: 'Female (Follicular)', ageMin: 18, ageMax: 50, gender: 'F', condition: 'Follicular', range: '<0.5', unit: 'ng/mL' },
        { ageGroup: 'Female (Ovulation)', ageMin: 18, ageMax: 50, gender: 'F', condition: 'Ovulation', range: '<0.5', unit: 'ng/mL' },
        { ageGroup: 'Female (Luteal)', ageMin: 18, ageMax: 50, gender: 'F', condition: 'Luteal', range: '3-25', unit: 'ng/mL' },
        { ageGroup: 'Female (Postmenopause)', ageMin: 50, gender: 'F', condition: 'Postmenopause', range: '<0.4', unit: 'ng/mL' },
      ],
    },
    {
      code: 'LH',
      name: 'Luteinizing Hormone',
      category: 'immunoassay',
      price: 220,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'IU/L',
      referenceRanges: [
        { ageGroup: 'Female (Follicular)', ageMin: 18, ageMax: 50, gender: 'F', condition: 'Follicular', range: '1.4-9.9', unit: 'IU/L' },
        { ageGroup: 'Female (Ovulation)', ageMin: 18, ageMax: 50, gender: 'F', condition: 'Ovulation', range: '6.2-17.2', unit: 'IU/L' },
        { ageGroup: 'Female (Luteal)', ageMin: 18, ageMax: 50, gender: 'F', condition: 'Luteal', range: '1.1-9.2', unit: 'IU/L' },
        { ageGroup: 'Female (Postmenopause)', ageMin: 50, gender: 'F', condition: 'Postmenopause', range: '19.3-100.6', unit: 'IU/L' },
        { ageGroup: 'Male', ageMin: 18, gender: 'M', range: '1.4-15.4', unit: 'IU/L' },
      ],
    },
    {
      code: 'FSH',
      name: 'Follicle Stimulating Hormone',
      category: 'immunoassay',
      price: 220,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'IU/L',
      referenceRanges: [
        { ageGroup: 'Female (Follicular)', ageMin: 18, ageMax: 50, gender: 'F', condition: 'Follicular', range: '1.4-9.9', unit: 'IU/L' },
        { ageGroup: 'Female (Ovulation)', ageMin: 18, ageMax: 50, gender: 'F', condition: 'Ovulation', range: '6.2-17.2', unit: 'IU/L' },
        { ageGroup: 'Female (Luteal)', ageMin: 18, ageMax: 50, gender: 
'F', condition: 'Luteal', range: '1.1-9.2', unit: 'IU/L' },
        { ageGroup: 'Female (Postmenopause)', ageMin: 50, gender: 'F', condition: 'Postmenopause', range: '19.3-100.6', unit: 'IU/L' },
        { ageGroup: 'Male', ageMin: 18, gender: 'M', range: '1.4-15.4', unit: 'IU/L' },
      ],
    },
    {
      code: 'PROLACTIN',
      name: 'Prolactin',
      category: 'immunoassay',
      price: 220,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'ng/mL',
      referenceRanges: [
        { ageGroup: 'Female', ageMin: 18, gender: 'F', range: '3-27', unit: 'ng/mL' },
        { ageGroup: 'Male', ageMin: 18, gender: 'M', range: '3-13', unit: 'ng/mL' },
      ],
    },
    {
      code: 'BHCG',
      name: 'Beta-HCG',
      category: 'immunoassay',
      price: 220,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'mIU/mL',
      referenceRanges: [
        { ageGroup: 'Non-pregnant', ageMin: 18, gender: 'F', range: '<5', unit: 'mIU/mL' },
        { ageGroup: 'Pregnancy (3 weeks)', ageMin: 18, gender: 'F', pregnancy: true, condition: '3 weeks', range: '5-50', unit: 'mIU/mL' },
        { ageGroup: 'Pregnancy (4 weeks)', ageMin: 18, gender: 'F', pregnancy: true, condition: '4 weeks', range: '5-426', unit: 'mIU/mL' },
        { ageGroup: 'Pregnancy (5 weeks)', ageMin: 18, gender: 'F', pregnancy: true, condition: '5 weeks', range: '18-7340', unit: 'mIU/mL' },
        { ageGroup: 'Pregnancy (6 weeks)', ageMin: 18, gender: 'F', pregnancy: true, condition: '6 weeks', range: '1080-56500', unit: 'mIU/mL' },
        { ageGroup: 'Pregnancy (7-8 weeks)', ageMin: 18, gender: 'F', pregnancy: true, condition: '7-8 weeks', range: '7650-229000', unit: 'mIU/mL' },
      ],
    },
    {
      code: 'TESTOSTERONE',
      name: 'Testosterone',
      category: 'immunoassay',
      price: 220,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'ng/dL',
      referenceRanges: [
        { ageGroup: 'Male (20-29 years)', ageMin: 20, ageMax: 29, gender: 'M', range: '400-1080', unit: 'ng/dL' },
        { ageGroup: 'Male (30-39 years)', ageMin: 30, ageMax: 39, gender: 'M', range: '350-890', unit: 'ng/dL' },
        { ageGroup: 'Male (40-49 years)', ageMin: 40, ageMax: 49, gender: 'M', range: '300-750', unit: 'ng/dL' },
        { ageGroup: 'Male (50-59 years)', ageMin: 50, ageMax: 59, gender: 'M', range: '250-650', unit: 'ng/dL' },
        { ageGroup: 'Male (60+ years)', ageMin: 60, gender: 'M', range: '200-550', unit: 'ng/dL' },
      ],
    },
    {
      code: 'VITD',
      name: 'Vitamin D',
      category: 'immunoassay',
      price: 255,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'ng/mL',
      referenceRanges: [
        { ageGroup: 'Deficiency', ageMin: 0, gender: 'all', range: '<20', unit: 'ng/mL' },
        { ageGroup: 'Insufficiency', ageMin: 0, gender: 'all', range: '20-30', unit: 'ng/mL' },
        { ageGroup: 'Sufficient', ageMin: 0, gender: 'all', range: '30-100', unit: 'ng/mL' },
        { ageGroup: 'Optimal', ageMin: 0, gender: 'all', range: '40-60', unit: 'ng/mL' },
      ],
    },
    {
      code: 'VITD_IA',
      name: 'Vitamin D [NEW] (Finecare)',
      category: 'immunoassay',
      price: 270,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'ng/mL',
      description: 'Vitamin D (25-OH) by Finecare immunoassay',
      referenceRanges: [
        { ageGroup: 'Deficiency', ageMin: 0, gender: 'all', range: '<20', unit: 'ng/mL' },
        { ageGroup: 'Insufficiency', ageMin: 0, gender: 'all', range: '20-30', unit: 'ng/mL' },
        { ageGroup: 'Sufficient', ageMin: 0, gender: 'all', range: '30-100', unit: 'ng/mL' },
      ],
    },
    {
      code: 'DDIMER',
      name: 'D-Dimer',
      category: 'immunoassay',
      price: 220,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'µg/mL FEU',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: '<0.5', unit: 'µg/mL FEU' },
        { ageGroup: 'Elevated', ageMin: 0, gender: 'all', range: '>0.5', unit: 'µg/mL FEU' },
      ],
    },
    {
      code: 'DDIMER_OS',
      name: 'D-Dimer (One Step)',
      category: 'immunoassay',
      price: 220,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'µg/mL FEU',
      description: 'D-Dimer rapid one-step immunoassay',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: '<0.5', unit: 'µg/mL FEU' },
        { ageGroup: 'Elevated', ageMin: 0, gender: 'all', range: '≥0.5', unit: 'µg/mL FEU' },
      ],
    },
    {
      code: 'MAU',
      name: 'Microalbumin (One Step)',
      category: 'immunoassay',
      price: 130,
      sampleType: 'urine',
      turnaroundTime: 30,
      isActive: true,
      unit: 'mg/L',
      description: 'Microalbumin urine rapid test (one-step)',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: '<20', unit: 'mg/L' },
        { ageGroup: 'Microalbuminuria', ageMin: 0, gender: 'all', range: '20-200', unit: 'mg/L' },
        { ageGroup: 'Macroalbuminuria', ageMin: 0, gender: 'all', range: '>200', unit: 'mg/L' },
      ],
    },

    // ==================== SEROLOGY ====================
    {
      code: 'HPYLORI',
      name: 'H. Pylori Rapid Test',
      category: 'serology',
      price: 100,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      description: 'Helicobacter pylori antibody rapid test',
    },
    {
      code: 'HPYLORI_IA',
      name: 'H. Pylori IgG Antibody (Finecare)',
      category: 'immunoassay',
      price: 270,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'AU/mL',
      description: 'Helicobacter pylori IgG antibody detection by Finecare immunoassay',
      referenceRanges: [
        { ageGroup: 'Negative', ageMin: 0, gender: 'all', range: '<10', unit: 'AU/mL' },
        { ageGroup: 'Positive', ageMin: 0, gender: 'all', range: '≥10', unit: 'AU/mL' },
      ],
    },
    {
      code: 'MALARIA',
      name: 'Malaria RDT',
      category: 'serology',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      description: 'Rapid malaria antigen test',
    },
    {
      code: 'HIV',
      name: 'HIV Rapid Test',
      category: 'serology',
      price: 100,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      description: 'HIV antibody rapid test',
    },
    {
      code: 'HBSAG',
      name: 'Hepatitis B Surface Antigen',
      category: 'serology',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      description: 'HBsAg rapid test',
    },
    {
      code: 'HCV',
      name: 'Hepatitis C Antibody',
      category: 'serology',
      price: 70,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      description: 'HCV antibody rapid test',
    },
    {
      code: 'WIDAL',
      name: 'Typhoid (IgM/IgG)',
      category: 'serology',
      price: 80,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      description: 'Typhoid rapid strip test — reports S. typhi IgM and IgG separately',
    },
    {
      code: 'VDRL',
      name: 'VDRL (Syphilis)',
      category: 'serology',
      price: 60,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      description: 'Syphilis screening test',
    },

    // ==================== MICROBIOLOGY ====================
    {
      code: 'HPAG',
      name: 'H. Pylori Antigen (Stool)',
      category: 'microbiology',
      price: 150,
      sampleType: 'stool',
      turnaroundTime: 60,
      isActive: true,
      description: 'Helicobacter pylori stool antigen detection',
    },

    // ==================== URINALYSIS ====================
    {
      code: 'URINE',
      name: 'Urinalysis',
      category: 'urinalysis',
      price: 90,
      sampleType: 'urine',
      turnaroundTime: 60,
      isActive: true,
      description: 'Complete urine analysis',
    },
    {
      code: 'UPROTEIN',
      name: 'Urine Protein',
      category: 'urinalysis',
      subcategory: 'Dipstick/Chemical',
      price: 100,
      sampleType: 'urine',
      turnaroundTime: 60,
      isActive: true,
      description: 'Urine protein dipstick test',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: 'Negative', unit: 'qualitative' },
      ],
    },
    {
      code: 'PREGNANCY',
      name: 'Pregnancy Test (Urine)',
      category: 'urinalysis',
      price: 100,
      sampleType: 'urine',
      turnaroundTime: 15,
      isActive: true,
      description: 'Urine HCG pregnancy test',
    },

    // ==================== URINALYSIS COMPONENTS ====================
    {
      code: 'URINE-COLOR',
      name: 'Urine Color',
      category: 'urinalysis',
      price: 0,
      sampleType: 'urine',
      turnaroundTime: 60,
      isActive: false,
      description: 'Physical examination - Color',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: 'Yellow to Amber', unit: 'qualitative' },
      ],
    },
    {
      code: 'URINE-CLARITY',
      name: 'Urine Clarity',
      category: 'urinalysis',
      price: 0,
      sampleType: 'urine',
      turnaroundTime: 60,
      isActive: false,
      description: 'Physical examination - Clarity/Appearance',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: 'Clear', unit: 'qualitative' },
      ],
    },
    {
      code: 'URINE-SG',
      name: 'Urine Specific Gravity',
      category: 'urinalysis',
      price: 0,
      sampleType: 'urine',
      turnaroundTime: 60,
      isActive: false,
      unit: 'SG',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: '1.000-1.030', unit: 'SG' },
      ],
    },
    {
      code: 'URINE-PH',
      name: 'Urine pH',
      category: 'urinalysis',
      price: 0,
      sampleType: 'urine',
      turnaroundTime: 60,
      isActive: false,
      unit: 'pH',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: '4.5-8.0', unit: 'pH' },
      ],
    },
    {
      code: 'URINE-PROTEIN',
      name: 'Urine Protein (Dipstick)',
      category: 'urinalysis',
      subcategory: 'Dipstick/Chemical',
      price: 0,
      sampleType: 'urine',
      turnaroundTime: 60,
      isActive: false,
      description: 'Chemical examination - Protein',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: 'Negative', unit: 'qualitative' },
      ],
    },
    {
      code: 'URINE-GLUCOSE',
      name: 'Urine Glucose',
      category: 'urinalysis',
      price: 0,
      sampleType: 'urine',
      turnaroundTime: 60,
      isActive: false,
      description: 'Chemical examination - Glucose',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: 'Negative', unit: 'qualitative' },
      ],
    },
    {
      code: 'URINE-KETONES',
      name: 'Urine Ketones',
      category: 'urinalysis',
      price: 0,
      sampleType: 'urine',
      turnaroundTime: 60,
      isActive: false,
      description: 'Chemical examination - Ketones',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: 'Negative', unit: 'qualitative' },
      ],
    },
    {
      code: 'URINE-BLOOD',
      name: 'Urine Blood',
      category: 'urinalysis',
      price: 0,
      sampleType: 'urine',
      turnaroundTime: 60,
      isActive: false,
      description: 'Chemical examination - Blood/Hemoglobin',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: 'Negative', unit: 'qualitative' },
      ],
    },
    {
      code: 'URINE-BILI',
      name: 'Urine Bilirubin',
      category: 'urinalysis',
      price: 0,
      sampleType: 'urine',
      turnaroundTime: 60,
      isActive: false,
      description: 'Chemical examination - Bilirubin',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: 'Negative', unit: 'qualitative' },
      ],
    },
    {
      code: 'URINE-URO',
      name: 'Urine Urobilinogen',
      category: 'urinalysis',
      price: 0,
      sampleType: 'urine',
      turnaroundTime: 60,
      isActive: false,
      unit: 'mg/dL',
      description: 'Chemical examination - Urobilinogen',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: '0.1-1.0', unit: 'mg/dL' },
      ],
    },
    {
      code: 'URINE-NITRITE',
      name: 'Urine Nitrite',
      category: 'urinalysis',
      price: 0,
      sampleType: 'urine',
      turnaroundTime: 60,
      isActive: false,
      description: 'Chemical examination - Nitrite',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: 'Negative', unit: 'qualitative' },
      ],
    },
    {
      code: 'URINE-LE',
      name: 'Urine Leukocyte Esterase',
      category: 'urinalysis',
      price: 0,
      sampleType: 'urine',
      turnaroundTime: 60,
      isActive: false,
      description: 'Chemical examination - Leukocyte Esterase',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: 'Negative', unit: 'qualitative' },
      ],
    },
    {
      code: 'URINE-RBC',
      name: 'Urine RBC',
      category: 'urinalysis',
      price: 0,
      sampleType: 'urine',
      turnaroundTime: 60,
      isActive: false,
      unit: '/HPF',
      description: 'Microscopic examination - Red Blood Cells',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: '0-3', unit: '/HPF' },
      ],
    },
    {
      code: 'URINE-WBC',
      name: 'Urine WBC',
      category: 'urinalysis',
      price: 0,
      sampleType: 'urine',
      turnaroundTime: 60,
      isActive: false,
      unit: '/HPF',
      description: 'Microscopic examination - White Blood Cells',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: '0-5', unit: '/HPF' },
      ],
    },
    {
      code: 'URINE-EPI',
      name: 'Urine Epithelial Cells',
      category: 'urinalysis',
      price: 0,
      sampleType: 'urine',
      turnaroundTime: 60,
      isActive: false,
      unit: '/HPF',
      description: 'Microscopic examination - Epithelial Cells',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: 'Few', unit: 'qualitative' },
      ],
    },
    {
      code: 'URINE-CASTS',
      name: 'Urine Casts',
      category: 'urinalysis',
      price: 0,
      sampleType: 'urine',
      turnaroundTime: 60,
      isActive: false,
      unit: '/LPF',
      description: 'Microscopic examination - Casts',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: '0-2 hyaline', unit: '/LPF' },
      ],
    },
    {
      code: 'URINE-CRYSTALS',
      name: 'Urine Crystals',
      category: 'urinalysis',
      price: 0,
      sampleType: 'urine',
      turnaroundTime: 60,
      isActive: false,
      description: 'Microscopic examination - Crystals',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: 'None or Few', unit: 'qualitative' },
      ],
    },
    {
      code: 'URINE-BACTERIA',
      name: 'Urine Bacteria',
      category: 'urinalysis',
      price: 0,
      sampleType: 'urine',
      turnaroundTime: 60,
      isActive: false,
      description: 'Microscopic examination - Bacteria',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: 'None', unit: 'qualitative' },
      ],
    },

    // ==================== ADDITIONAL CHEMISTRY TESTS ====================
    {
      code: 'FE',
      name: 'Iron',
      category: 'chemistry',
      price: 80,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'µg/dL',
      referenceRanges: [
        { ageGroup: 'Male', ageMin: 18, gender: 'M', range: '65-175', unit: 'µg/dL' },
        { ageGroup: 'Female', ageMin: 18, gender: 'F', range: '50-170', unit: 'µg/dL' },
      ],
    },
    {
      code: 'MG',
      name: 'Magnesium',
      category: 'chemistry',
      price: 150,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mg/dL',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '1.7-2.2', unit: 'mg/dL' },
      ],
    },
    {
      code: 'ZN',
      name: 'Zinc',
      category: 'chemistry',
      price: 150,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'µg/dL',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '70-120', unit: 'µg/dL' },
      ],
    },
    {
      code: 'CO2',
      name: 'Carbon Dioxide',
      category: 'chemistry',
      price: 80,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mmol/L',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '23-29', unit: 'mmol/L' },
      ],
    },
    {
      code: 'TCO2',
      name: 'Total Carbon Dioxide',
      category: 'chemistry',
      price: 35,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mmol/L',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '22-28', unit: 'mmol/L' },
      ],
    },
    {
      code: 'LDH',
      name: 'Lactate Dehydrogenase',
      category: 'chemistry',
      price: 180,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'U/L',
      referenceRanges: [
        { ageGroup: 'Adult', ageMin: 18, gender: 'all', range: '140-280', unit: 'U/L' },
      ],
    },

    // ==================== ADDITIONAL IMMUNOASSAY TESTS ====================
    {
      code: 'T3',
      name: 'Total Triiodothyronine',
      category: 'immunoassay',
      price: 220,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'ng/dL',
      referenceRanges: [
        { ageGroup: 'Adult', ageMin: 18, gender: 'all', range: '80-200', unit: 'ng/dL' },
      ],
    },
    {
      code: 'T4',
      name: 'Total Thyroxine',
      category: 'immunoassay',
      price: 220,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'µg/dL',
      referenceRanges: [
        { ageGroup: 'Adult', ageMin: 18, gender: 'all', range: '5.0-12.0', unit: 'µg/dL' },
      ],
    },
    {
      code: 'AMH',
      name: 'Anti-Müllerian Hormone',
      category: 'immunoassay',
      price: 270,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'ng/mL',
      referenceRanges: [
        { ageGroup: 'Female (High)', ageMin: 18, ageMax: 35, gender: 'F', range: '>3.0', unit: 'ng/mL' },
        { ageGroup: 'Female (Normal)', ageMin: 18, ageMax: 35, gender: 'F', range: '1.0-3.0', unit: 'ng/mL' },
        { ageGroup: 'Female (Low)', ageMin: 18, ageMax: 35, gender: 'F', range: '0.3-1.0', unit: 'ng/mL' },
        { ageGroup: 'Female (Very Low)', ageMin: 35, gender: 'F', range: '<0.3', unit: 'ng/mL' },
      ],
    },
    {
      code: 'CA125',
      name: 'Cancer Antigen 125',
      category: 'immunoassay',
      price: 270,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'U/mL',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 18, gender: 'all', range: '<35', unit: 'U/mL' },
      ],
    },
    {
      code: 'IL6',
      name: 'Interleukin-6',
      category: 'immunoassay',
      price: 320,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'pg/mL',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: '<7.0', unit: 'pg/mL' },
      ],
    },
    {
      code: 'FERRITIN',
      name: 'Ferritin',
      category: 'immunoassay',
      price: 270,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'ng/mL',
      referenceRanges: [
        { ageGroup: 'Male', ageMin: 18, gender: 'M', range: '24-336', unit: 'ng/mL' },
        { ageGroup: 'Female', ageMin: 18, gender: 'F', range: '11-307', unit: 'ng/mL' },
      ],
    },
    {
      code: 'VITB12',
      name: 'Vitamin B12',
      category: 'immunoassay',
      price: 370,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'pg/mL',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: '200-900', unit: 'pg/mL' },
        { ageGroup: 'Deficiency', ageMin: 0, gender: 'all', range: '<200', unit: 'pg/mL' },
      ],
    },
    {
      code: 'CORTISOL',
      name: 'Cortisol',
      category: 'immunoassay',
      price: 270,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'µg/dL',
      referenceRanges: [
        { ageGroup: 'AM (7-9am)', ageMin: 18, gender: 'all', condition: 'Morning', range: '5-25', unit: 'µg/dL' },
        { ageGroup: 'PM (3-5pm)', ageMin: 18, gender: 'all', condition: 'Afternoon', range: '3-16', unit: 'µg/dL' },
      ],
    },
    {
      code: 'CKMB',
      name: 'Creatine Kinase-MB',
      category: 'immunoassay',
      price: 270,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'ng/mL',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: '<5.0', unit: 'ng/mL' },
      ],
    },
    {
      code: 'MYO',
      name: 'Myoglobin',
      category: 'immunoassay',
      price: 270,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'ng/mL',
      referenceRanges: [
        { ageGroup: 'Male', ageMin: 18, gender: 'M', range: '28-72', unit: 'ng/mL' },
        { ageGroup: 'Female', ageMin: 18, gender: 'F', range: '25-58', unit: 'ng/mL' },
      ],
    },
    {
      code: 'FPSA',
      name: 'Free PSA',
      category: 'immunoassay',
      price: 240,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'ng/mL',
      referenceRanges: [
        { ageGroup: 'Free/Total PSA Ratio', ageMin: 18, gender: 'M', range: '>0.25', unit: 'ratio' },
      ],
    },
    {
      code: 'CTNT',
      name: 'Troponin T',
      category: 'immunoassay',
      price: 290,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'ng/mL',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: '<0.01', unit: 'ng/mL', criticalHigh: '0.1' },
      ],
    },
    {
      code: 'MAU',
      name: 'Microalbumin',
      category: 'immunoassay',
      price: 200,
      sampleType: 'urine',
      turnaroundTime: 30,
      isActive: true,
      unit: 'mg/L',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: '<30', unit: 'mg/L' },
        { ageGroup: 'Microalbuminuria', ageMin: 0, gender: 'all', range: '30-300', unit: 'mg/L' },
      ],
    },
    {
      code: 'CYSC',
      name: 'Cystatin C',
      category: 'immunoassay',
      price: 200,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'mg/L',
      referenceRanges: [
        { ageGroup: 'Adult', ageMin: 18, gender: 'all', range: '0.5-1.0', unit: 'mg/L' },
      ],
    },
    {
      code: 'NGAL',
      name: 'Neutrophil Gelatinase-Associated Lipocalin',
      category: 'immunoassay',
      price: 260,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'ng/mL',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: '<150', unit: 'ng/mL' },
      ],
    },
    {
      code: 'B2MG',
      name: 'Beta-2 Microglobulin',
      category: 'immunoassay',
      price: 305,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'mg/L',
      referenceRanges: [
        { ageGroup: 'Adult', ageMin: 18, gender: 'all', range: '0.8-2.2', unit: 'mg/L' },
      ],
    },
    {
      code: 'IFOB',
      name: 'Immunochemical Fecal Occult Blood',
      category: 'immunoassay',
      price: 330,
      sampleType: 'stool',
      turnaroundTime: 30,
      isActive: true,
      description: 'Fecal immunochemical test for occult blood',
      referenceRanges: [
        { ageGroup: 'Negative', ageMin: 0, gender: 'all', range: 'Negative', unit: 'qualitative' },
      ],
    },
    {
      code: 'IGE',
      name: 'Total IgE',
      category: 'immunoassay',
      price: 325,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'IU/mL',
      referenceRanges: [
        { ageGroup: 'Adult', ageMin: 18, gender: 'all', range: '<100', unit: 'IU/mL' },
      ],
    },
    {
      code: 'ASO',
      name: 'Anti-Streptolysin O',
      category: 'immunoassay',
      price: 270,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'IU/mL',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: '<200', unit: 'IU/mL' },
      ],
    },
    {
      code: 'RF',
      name: 'Rheumatoid Factor',
      category: 'immunoassay',
      price: 270,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'IU/mL',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: '<14', unit: 'IU/mL' },
      ],
    },
    {
      code: 'ANTICCP',
      name: 'Anti-CCP',
      category: 'immunoassay',
      price: 270,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'U/mL',
      referenceRanges: [
        { ageGroup: 'Negative', ageMin: 0, gender: 'all', range: '<20', unit: 'U/mL' },
        { ageGroup: 'Positive', ageMin: 0, gender: 'all', range: '≥20', unit: 'U/mL' },
      ],
    },

    // ==================== COAGULATION TESTS ====================
    {
      code: 'PT',
      name: 'Prothrombin Time',
      category: 'hematology',
      price: 175,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'seconds',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: '11-13.5', unit: 'seconds' },
        { ageGroup: 'INR', ageMin: 0, gender: 'all', range: '0.8-1.2', unit: 'INR' },
      ],
    },
    {
      code: 'APTT',
      name: 'Activated Partial Thromboplastin Time',
      category: 'hematology',
      price: 175,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'seconds',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: '25-35', unit: 'seconds' },
      ],
    },
    {
      code: 'ACT',
      name: 'Activated Clotting Time',
      category: 'hematology',
      price: 175,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'seconds',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: '70-120', unit: 'seconds' },
      ],
    },
    {
      code: 'FIB',
      name: 'Fibrinogen',
      category: 'hematology',
      price: 175,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'mg/dL',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: '200-400', unit: 'mg/dL' },
      ],
    },

    // ==================== ADDITIONAL HEMATOLOGY TESTS ====================
    {
      code: 'BLOODGROUP',
      name: 'Blood Grouping',
      category: 'hematology',
      price: 70,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      description: 'ABO and Rh blood grouping',
    },
    {
      code: 'SICKLE',
      name: 'Sickle Cell Screen',
      category: 'hematology',
      price: 100,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      description: 'Sickle cell disease screening test',
    },

    // ==================== MORE SEROLOGY TESTS ====================
    {
      code: 'GONORRHEA',
      name: 'Gonorrhea Test',
      category: 'serology',
      price: 150,
      sampleType: 'swab',
      turnaroundTime: 60,
      isActive: true,
      description: 'Gonorrhea antigen detection',
    },
    {
      code: 'CHLAMYDIA',
      name: 'Chlamydia Test',
      category: 'serology',
      price: 150,
      sampleType: 'swab',
      turnaroundTime: 60,
      isActive: true,
      description: 'Chlamydia antigen detection',
    },
    {
      code: 'HSV',
      name: 'Herpes Simplex Virus',
      category: 'serology',
      price: 150,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      description: 'HSV antibody test',
    },
    {
      code: 'HIVP24',
      name: 'HIV P24 Antigen',
      category: 'serology',
      price: 150,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      description: 'HIV P24 antigen test for early detection',
    },
    {
      code: 'STOOLMICRO',
      name: 'Stool Microscopy',
      category: 'microbiology',
      price: 100,
      sampleType: 'stool',
      turnaroundTime: 120,
      isActive: true,
      description: 'Microscopic examination of stool for parasites and ova',
    },
  ];

  // Insert all tests
  console.log(`Inserting ${tests.length} tests into database...`);
  const insertedTests = await testCatalogModel.insertMany(tests);
  console.log(`Successfully inserted ${insertedTests.length} tests`);

  console.log('Test catalog seeding completed successfully!');
  await app.close();
}

seedTestCatalog()
  .then(() => {
    console.log('Seeding process finished');
    process.exit(0);
  })
  .catch((error) => {
    console.error('Error seeding test catalog:', error);
    process.exit(1);
  });
