import { NestFactory } from '@nestjs/core';
import { AppModule } from '../app.module';
import { Model } from 'mongoose';
import { TestCatalog } from './schemas/test-catalog.schema';

async function seedTestCatalog() {
  const app = await NestFactory.createApplicationContext(AppModule);
  
  const testCatalogModel = app.get<Model<TestCatalog>>('TestCatalogModel');

  console.log('Starting comprehensive test catalog seeding with age/gender-specific ranges...');

  // Clear existing test catalog
  await testCatalogModel.deleteMany({});
  console.log('Cleared existing test catalog');

  const tests = [
    // ==================== HAEMATOLOGY (ZYBIO ZS-2) ====================
    {
      code: 'HB',
      name: 'Hemoglobin',
      category: 'hematology',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      description: 'Hemoglobin concentration measurement',
      unit: 'g/dL',
      referenceRanges: [
        { ageGroup: 'Newborn (0-2 weeks)', ageMin: 0, ageMax: 0.04, gender: 'all', range: '14.5-22.5', unit: 'g/dL', criticalLow: '7.0', criticalHigh: '20.0' },
        { ageGroup: '2 weeks - 1 month', ageMin: 0.04, ageMax: 0.08, gender: 'all', range: '12.0-20.0', unit: 'g/dL' },
        { ageGroup: '1-2 months', ageMin: 0.08, ageMax: 0.17, gender: 'all', range: '10.0-18.0', unit: 'g/dL' },
        { ageGroup: '2-6 months', ageMin: 0.17, ageMax: 0.5, gender: 'all', range: '9.5-14.0', unit: 'g/dL' },
        { ageGroup: '6 months - 2 years', ageMin: 0.5, ageMax: 2, gender: 'all', range: '10.5-13.5', unit: 'g/dL' },
        { ageGroup: '2-6 years', ageMin: 2, ageMax: 6, gender: 'all', range: '11.5-13.5', unit: 'g/dL' },
        { ageGroup: '6-12 years', ageMin: 6, ageMax: 12, gender: 'all', range: '11.5-15.5', unit: 'g/dL' },
        { ageGroup: '12-18 years', ageMin: 12, ageMax: 18, gender: 'M', range: '13.0-16.0', unit: 'g/dL' },
        { ageGroup: '12-18 years', ageMin: 12, ageMax: 18, gender: 'F', range: '12.0-16.0', unit: 'g/dL' },
        { ageGroup: 'Adult (18-65 years)', ageMin: 18, ageMax: 65, gender: 'M', range: '13.5-18.0', unit: 'g/dL', criticalLow: '7.0', criticalHigh: '20.0' },
        { ageGroup: 'Adult (18-65 years)', ageMin: 18, ageMax: 65, gender: 'F', range: '12.0-16.0', unit: 'g/dL', criticalLow: '7.0', criticalHigh: '20.0' },
        { ageGroup: 'Elderly (>65 years)', ageMin: 65, gender: 'M', range: '12.0-17.0', unit: 'g/dL' },
        { ageGroup: 'Elderly (>65 years)', ageMin: 65, gender: 'F', range: '11.0-15.0', unit: 'g/dL' },
        { ageGroup: 'Pregnancy', gender: 'F', pregnancy: true, range: '11.0-14.0', unit: 'g/dL' },
      ],
    },
    {
      code: 'HCT',
      name: 'Hematocrit',
      category: 'hematology',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      description: 'Packed cell volume',
      unit: '%',
      referenceRanges: [
        { ageGroup: 'Newborn', ageMin: 0, ageMax: 0.08, gender: 'all', range: '44-64', unit: '%', criticalLow: '20', criticalHigh: '60' },
        { ageGroup: '1 month', ageMin: 0.08, ageMax: 0.17, gender: 'all', range: '31-55', unit: '%' },
        { ageGroup: '6 months - 2 years', ageMin: 0.5, ageMax: 2, gender: 'all', range: '33-39', unit: '%' },
        { ageGroup: '2-6 years', ageMin: 2, ageMax: 6, gender: 'all', range: '34-40', unit: '%' },
        { ageGroup: '6-12 years', ageMin: 6, ageMax: 12, gender: 'all', range: '35-45', unit: '%' },
        { ageGroup: '12-18 years', ageMin: 12, ageMax: 18, gender: 'M', range: '37-49', unit: '%' },
        { ageGroup: '12-18 years', ageMin: 12, ageMax: 18, gender: 'F', range: '36-46', unit: '%' },
        { ageGroup: 'Adult (18-65 years)', ageMin: 18, ageMax: 65, gender: 'M', range: '40-54', unit: '%', criticalLow: '20', criticalHigh: '60' },
        { ageGroup: 'Adult (18-65 years)', ageMin: 18, ageMax: 65, gender: 'F', range: '36-48', unit: '%', criticalLow: '20', criticalHigh: '60' },
        { ageGroup: 'Elderly (>65 years)', ageMin: 65, gender: 'M', range: '37-51', unit: '%' },
        { ageGroup: 'Elderly (>65 years)', ageMin: 65, gender: 'F', range: '34-46', unit: '%' },
      ],
    },
    {
      code: 'RBC',
      name: 'Red Blood Cell Count',
      category: 'hematology',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'x10⁶/µL',
      referenceRanges: [
        { ageGroup: 'Newborn', ageMin: 0, ageMax: 0.08, gender: 'all', range: '4.1-6.1', unit: 'x10⁶/µL' },
        { ageGroup: '1-3 months', ageMin: 0.08, ageMax: 0.25, gender: 'all', range: '3.2-4.8', unit: 'x10⁶/µL' },
        { ageGroup: '6 months - 2 years', ageMin: 0.5, ageMax: 2, gender: 'all', range: '3.7-5.3', unit: 'x10⁶/µL' },
        { ageGroup: '2-6 years', ageMin: 2, ageMax: 6, gender: 'all', range: '3.9-5.3', unit: 'x10⁶/µL' },
        { ageGroup: '6-12 years', ageMin: 6, ageMax: 12, gender: 'all', range: '4.0-5.2', unit: 'x10⁶/µL' },
        { ageGroup: '12-18 years', ageMin: 12, ageMax: 18, gender: 'M', range: '4.5-5.3', unit: 'x10⁶/µL' },
        { ageGroup: '12-18 years', ageMin: 12, ageMax: 18, gender: 'F', range: '4.1-5.1', unit: 'x10⁶/µL' },
        { ageGroup: 'Adult (18-65 years)', ageMin: 18, ageMax: 65, gender: 'M', range: '4.5-5.9', unit: 'x10⁶/µL' },
        { ageGroup: 'Adult (18-65 years)', ageMin: 18, ageMax: 65, gender: 'F', range: '4.1-5.1', unit: 'x10⁶/µL' },
        { ageGroup: 'Elderly (>65 years)', ageMin: 65, gender: 'M', range: '4.0-5.5', unit: 'x10⁶/µL' },
        { ageGroup: 'Elderly (>65 years)', ageMin: 65, gender: 'F', range: '3.8-5.0', unit: 'x10⁶/µL' },
      ],
    },
    {
      code: 'WBC',
      name: 'White Blood Cell Count',
      category: 'hematology',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'x10³/µL',
      referenceRanges: [
        { ageGroup: 'Newborn (0-2 weeks)', ageMin: 0, ageMax: 0.04, gender: 'all', range: '9.0-30.0', unit: 'x10³/µL', criticalLow: '2.0', criticalHigh: '30.0' },
        { ageGroup: '2 weeks - 1 month', ageMin: 0.04, ageMax: 0.08, gender: 'all', range: '5.0-21.0', unit: 'x10³/µL' },
        { ageGroup: '1-6 months', ageMin: 0.08, ageMax: 0.5, gender: 'all', range: '6.0-17.5', unit: 'x10³/µL' },
        { ageGroup: '6 months - 2 years', ageMin: 0.5, ageMax: 2, gender: 'all', range: '6.0-17.0', unit: 'x10³/µL' },
        { ageGroup: '2-6 years', ageMin: 2, ageMax: 6, gender: 'all', range: '5.0-15.5', unit: 'x10³/µL' },
        { ageGroup: '6-12 years', ageMin: 6, ageMax: 12, gender: 'all', range: '4.5-13.5', unit: 'x10³/µL' },
        { ageGroup: '12-18 years', ageMin: 12, ageMax: 18, gender: 'all', range: '4.5-13.0', unit: 'x10³/µL' },
        { ageGroup: 'Adult (18-65 years)', ageMin: 18, ageMax: 65, gender: 'all', range: '4.0-11.0', unit: 'x10³/µL', criticalLow: '2.0', criticalHigh: '30.0' },
        { ageGroup: 'Elderly (>65 years)', ageMin: 65, gender: 'all', range: '3.5-10.5', unit: 'x10³/µL' },
      ],
    },
    {
      code: 'PLT',
      name: 'Platelet Count',
      category: 'hematology',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'x10³/µL',
      referenceRanges: [
        { ageGroup: 'Newborn', ageMin: 0, ageMax: 0.08, gender: 'all', range: '150-450', unit: 'x10³/µL', criticalLow: '50', criticalHigh: '1000' },
        { ageGroup: 'Infant', ageMin: 0.08, ageMax: 2, gender: 'all', range: '200-450', unit: 'x10³/µL', criticalLow: '50', criticalHigh: '1000' },
        { ageGroup: 'Child', ageMin: 2, ageMax: 18, gender: 'all', range: '150-450', unit: 'x10³/µL', criticalLow: '50', criticalHigh: '1000' },
        { ageGroup: 'Adult', ageMin: 18, gender: 'all', range: '150-400', unit: 'x10³/µL', criticalLow: '50', criticalHigh: '1000' },
      ],
    },
    {
      code: 'MCV',
      name: 'Mean Corpuscular Volume',
      category: 'hematology',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'fL',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '80-100', unit: 'fL' },
      ],
    },
    {
      code: 'MCH',
      name: 'Mean Corpuscular Hemoglobin',
      category: 'hematology',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'pg',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '27-32', unit: 'pg' },
      ],
    },
    {
      code: 'MCHC',
      name: 'Mean Corpuscular Hemoglobin Concentration',
      category: 'hematology',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'g/dL',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '32-36', unit: 'g/dL' },
      ],
    },
    {
      code: 'RDW',
      name: 'Red Cell Distribution Width',
      category: 'hematology',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: '%',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '11.5-14.5', unit: '%' },
      ],
    },
    {
      code: 'NEUT',
      name: 'Neutrophils',
      category: 'hematology',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: '%',
      referenceRanges: [
        { ageGroup: 'Adult', ageMin: 18, gender: 'all', range: '40-70', unit: '%' },
        { ageGroup: 'Adult (absolute)', ageMin: 18, gender: 'all', range: '2.0-7.5', unit: 'x10³/µL', criticalLow: '1.0' },
      ],
    },
    {
      code: 'LYMPH',
      name: 'Lymphocytes',
      category: 'hematology',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: '%',
      referenceRanges: [
        { ageGroup: 'Adult', ageMin: 18, gender: 'all', range: '20-40', unit: '%' },
        { ageGroup: 'Adult (absolute)', ageMin: 18, gender: 'all', range: '1.0-4.0', unit: 'x10³/µL' },
      ],
    },
    {
      code: 'MONO',
      name: 'Monocytes',
      category: 'hematology',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: '%',
      referenceRanges: [
        { ageGroup: 'Adult', ageMin: 18, gender: 'all', range: '2-10', unit: '%' },
        { ageGroup: 'Adult (absolute)', ageMin: 18, gender: 'all', range: '0.2-1.0', unit: 'x10³/µL' },
      ],
    },
    {
      code: 'EOS',
      name: 'Eosinophils',
      category: 'hematology',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: '%',
      referenceRanges: [
        { ageGroup: 'Adult', ageMin: 18, gender: 'all', range: '1-6', unit: '%' },
        { ageGroup: 'Adult (absolute)', ageMin: 18, gender: 'all', range: '0.0-0.5', unit: 'x10³/µL' },
      ],
    },
    {
      code: 'BASO',
      name: 'Basophils',
      category: 'hematology',
      price: 50,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: '%',
      referenceRanges: [
        { ageGroup: 'Adult', ageMin: 18, gender: 'all', range: '0-2', unit: '%' },
        { ageGroup: 'Adult (absolute)', ageMin: 18, gender: 'all', range: '0.0-0.2', unit: 'x10³/µL' },
      ],
    },
    {
      code: 'ESR',
      name: 'Erythrocyte Sedimentation Rate',
      category: 'hematology',
      price: 100,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mm/hr',
      referenceRanges: [
        { ageGroup: 'Newborn', ageMin: 0, ageMax: 0.04, gender: 'all', range: '0-2', unit: 'mm/hr' },
        { ageGroup: 'Child', ageMin: 0.04, ageMax: 18, gender: 'all', range: '0-10', unit: 'mm/hr' },
        { ageGroup: 'Adult Male', ageMin: 18, ageMax: 50, gender: 'M', range: '0-15', unit: 'mm/hr' },
        { ageGroup: 'Adult Female', ageMin: 18, ageMax: 50, gender: 'F', range: '0-20', unit: 'mm/hr' },
        { ageGroup: 'Elderly Male', ageMin: 50, gender: 'M', range: '0-20', unit: 'mm/hr' },
        { ageGroup: 'Elderly Female', ageMin: 50, gender: 'F', range: '0-30', unit: 'mm/hr' },
      ],
    },
    {
      code: 'FBC',
      name: 'Full Blood Count',
      category: 'hematology',
      price: 200,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      description: 'Complete blood count with differential',
    },

    // ==================== CLINICAL CHEMISTRY (ZYBIO EXC-200) ====================
    {
      code: 'ALT',
      name: 'Alanine Aminotransferase',
      category: 'chemistry',
      price: 150,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'U/L',
      referenceRanges: [
        { ageGroup: 'Adult Male', ageMin: 18, ageMax: 65, gender: 'M', range: '7-56', unit: 'U/L' },
        { ageGroup: 'Adult Female', ageMin: 18, ageMax: 65, gender: 'F', range: '7-45', unit: 'U/L' },
        { ageGroup: 'Elderly', ageMin: 65, gender: 'all', range: '7-50', unit: 'U/L' },
      ],
    },
    {
      code: 'AST',
      name: 'Aspartate Aminotransferase',
      category: 'chemistry',
      price: 150,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'U/L',
      referenceRanges: [
        { ageGroup: 'Adult Male', ageMin: 18, ageMax: 65, gender: 'M', range: '10-40', unit: 'U/L' },
        { ageGroup: 'Adult Female', ageMin: 18, ageMax: 65, gender: 'F', range: '10-35', unit: 'U/L' },
        { ageGroup: 'Elderly', ageMin: 65, gender: 'all', range: '10-40', unit: 'U/L' },
      ],
    },
    {
      code: 'ALP',
      name: 'Alkaline Phosphatase',
      category: 'chemistry',
      price: 150,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'U/L',
      referenceRanges: [
        { ageGroup: 'Newborn', ageMin: 0, ageMax: 0.08, gender: 'all', range: '75-400', unit: 'U/L' },
        { ageGroup: '1 month - 1 year', ageMin: 0.08, ageMax: 1, gender: 'all', range: '82-383', unit: 'U/L' },
        { ageGroup: '1-3 years', ageMin: 1, ageMax: 3, gender: 'all', range: '104-345', unit: 'U/L' },
        { ageGroup: '4-6 years', ageMin: 4, ageMax: 6, gender: 'all', range: '93-309', unit: 'U/L' },
        { ageGroup: '7-9 years', ageMin: 7, ageMax: 9, gender: 'all', range: '69-325', unit: 'U/L' },
        { ageGroup: '10-12 years', ageMin: 10, ageMax: 12, gender: 'all', range: '42-362', unit: 'U/L' },
        { ageGroup: '13-15 years', ageMin: 13, ageMax: 15, gender: 'M', range: '74-390', unit: 'U/L' },
        { ageGroup: '13-15 years', ageMin: 13, ageMax: 15, gender: 'F', range: '50-162', unit: 'U/L' },
        { ageGroup: '16-18 years', ageMin: 16, ageMax: 18, gender: 'M', range: '52-171', unit: 'U/L' },
        { ageGroup: '16-18 years', ageMin: 16, ageMax: 18, gender: 'F', range: '47-119', unit: 'U/L' },
        { ageGroup: 'Adult', ageMin: 18, ageMax: 65, gender: 'all', range: '44-147', unit: 'U/L' },
        { ageGroup: 'Elderly', ageMin: 65, gender: 'all', range: '44-147', unit: 'U/L' },
      ],
    },
    {
      code: 'GGT',
      name: 'Gamma-Glutamyl Transferase',
      category: 'chemistry',
      price: 150,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'U/L',
      referenceRanges: [
        { ageGroup: 'Adult Male', ageMin: 18, gender: 'M', range: '8-61', unit: 'U/L' },
        { ageGroup: 'Adult Female', ageMin: 18, gender: 'F', range: '5-36', unit: 'U/L' },
      ],
    },
    {
      code: 'TBIL',
      name: 'Total Bilirubin',
      category: 'chemistry',
      price: 150,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mg/dL',
      referenceRanges: [
        { ageGroup: 'Newborn (0-24 hours)', ageMin: 0, ageMax: 0.003, gender: 'all', range: '1.0-12.0', unit: 'mg/dL', criticalHigh: '15.0' },
        { ageGroup: 'Newborn (3-5 days)', ageMin: 0.008, ageMax: 0.014, gender: 'all', range: '1.5-12.0', unit: 'mg/dL', criticalHigh: '15.0' },
        { ageGroup: 'Child (6 days - 18 years)', ageMin: 0.016, ageMax: 18, gender: 'all', range: '0.3-1.2', unit: 'mg/dL' },
        { ageGroup: 'Adult', ageMin: 18, gender: 'all', range: '0.3-1.2', unit: 'mg/dL', criticalHigh: '15.0' },
      ],
    },
    {
      code: 'DBIL',
      name: 'Direct Bilirubin',
      category: 'chemistry',
      price: 150,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mg/dL',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '0.0-0.3', unit: 'mg/dL' },
      ],
    },
    {
      code: 'IBIL',
      name: 'Indirect Bilirubin',
      category: 'chemistry',
      price: 150,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mg/dL',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '0.2-0.8', unit: 'mg/dL' },
      ],
    },
    {
      code: 'TP',
      name: 'Total Protein',
      category: 'chemistry',
      price: 150,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'g/dL',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '6.0-8.3', unit: 'g/dL' },
      ],
    },
    {
      code: 'ALB',
      name: 'Albumin',
      category: 'chemistry',
      price: 150,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'g/dL',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '3.5-5.5', unit: 'g/dL' },
      ],
    },
    {
      code: 'GLOB',
      name: 'Globulin',
      category: 'chemistry',
      price: 150,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'g/dL',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '2.0-3.5', unit: 'g/dL' },
      ],
    },
    {
      code: 'CREAT',
      name: 'Creatinine',
      category: 'chemistry',
      price: 150,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mg/dL',
      referenceRanges: [
        { ageGroup: 'Infant (0-1 year)', ageMin: 0, ageMax: 1, gender: 'all', range: '0.2-0.4', unit: 'mg/dL' },
        { ageGroup: 'Child (1-12 years)', ageMin: 1, ageMax: 12, gender: 'all', range: '0.3-0.7', unit: 'mg/dL' },
        { ageGroup: 'Adolescent (12-18 years)', ageMin: 12, ageMax: 18, gender: 'all', range: '0.5-1.0', unit: 'mg/dL' },
        { ageGroup: 'Adult Male', ageMin: 18, ageMax: 65, gender: 'M', range: '0.7-1.3', unit: 'mg/dL', criticalHigh: '5.0' },
        { ageGroup: 'Adult Female', ageMin: 18, ageMax: 65, gender: 'F', range: '0.6-1.1', unit: 'mg/dL', criticalHigh: '5.0' },
        { ageGroup: 'Elderly Male', ageMin: 65, gender: 'M', range: '0.8-1.3', unit: 'mg/dL' },
        { ageGroup: 'Elderly Female', ageMin: 65, gender: 'F', range: '0.6-1.2', unit: 'mg/dL' },
      ],
    },
    {
      code: 'UREA',
      name: 'Urea',
      category: 'chemistry',
      price: 150,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mg/dL',
      referenceRanges: [
        { ageGroup: 'Child', ageMin: 0, ageMax: 18, gender: 'all', range: '5-18', unit: 'mg/dL' },
        { ageGroup: 'Adult', ageMin: 18, ageMax: 65, gender: 'all', range: '7-20', unit: 'mg/dL' },
        { ageGroup: 'Elderly', ageMin: 65, gender: 'all', range: '8-23', unit: 'mg/dL' },
      ],
    },
    {
      code: 'UA',
      name: 'Uric Acid',
      category: 'chemistry',
      price: 150,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mg/dL',
      referenceRanges: [
        { ageGroup: 'Child', ageMin: 0, ageMax: 18, gender: 'all', range: '2.0-5.5', unit: 'mg/dL' },
        { ageGroup: 'Adult Male', ageMin: 18, gender: 'M', range: '3.5-7.2', unit: 'mg/dL' },
        { ageGroup: 'Adult Female (premenopausal)', ageMin: 18, ageMax: 50, gender: 'F', range: '2.6-6.0', unit: 'mg/dL' },
        { ageGroup: 'Adult Female (postmenopausal)', ageMin: 50, gender: 'F', range: '3.5-7.2', unit: 'mg/dL' },
      ],
    },
    {
      code: 'CHOL',
      name: 'Total Cholesterol',
      category: 'chemistry',
      price: 200,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mg/dL',
      referenceRanges: [
        { ageGroup: 'Desirable', ageMin: 18, gender: 'all', range: '<200', unit: 'mg/dL' },
        { ageGroup: 'Borderline High', ageMin: 18, gender: 'all', range: '200-239', unit: 'mg/dL' },
        { ageGroup: 'High', ageMin: 18, gender: 'all', range: '≥240', unit: 'mg/dL' },
      ],
    },
    {
      code: 'TG',
      name: 'Triglycerides',
      category: 'chemistry',
      price: 200,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mg/dL',
      referenceRanges: [
        { ageGroup: 'Desirable', ageMin: 18, gender: 'all', range: '<150', unit: 'mg/dL' },
        { ageGroup: 'Borderline High', ageMin: 18, gender: 'all', range: '150-199', unit: 'mg/dL' },
        { ageGroup: 'High', ageMin: 18, gender: 'all', range: '≥200', unit: 'mg/dL' },
      ],
    },
    {
      code: 'HDL',
      name: 'HDL Cholesterol',
      category: 'chemistry',
      price: 200,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mg/dL',
      referenceRanges: [
        { ageGroup: 'Male (Optimal)', ageMin: 18, gender: 'M', range: '>40', unit: 'mg/dL' },
        { ageGroup: 'Female (Optimal)', ageMin: 18, gender: 'F', range: '>50', unit: 'mg/dL' },
      ],
    },
    {
      code: 'LDL',
      name: 'LDL Cholesterol',
      category: 'chemistry',
      price: 200,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mg/dL',
      referenceRanges: [
        { ageGroup: 'Optimal', ageMin: 18, gender: 'all', range: '<100', unit: 'mg/dL' },
        { ageGroup: 'Near Optimal', ageMin: 18, gender: 'all', range: '100-129', unit: 'mg/dL' },
        { ageGroup: 'Borderline High', ageMin: 18, gender: 'all', range: '130-159', unit: 'mg/dL' },
        { ageGroup: 'High', ageMin: 18, gender: 'all', range: '≥160', unit: 'mg/dL' },
      ],
    },
    {
      code: 'VLDL',
      name: 'VLDL Cholesterol',
      category: 'chemistry',
      price: 200,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mg/dL',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '<30', unit: 'mg/dL' },
      ],
    },
    {
      code: 'GLU',
      name: 'Fasting Blood Glucose',
      category: 'chemistry',
      price: 100,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mg/dL',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 18, gender: 'all', range: '70-100', unit: 'mg/dL', criticalLow: '50', criticalHigh: '500' },
        { ageGroup: 'Prediabetes', ageMin: 18, gender: 'all', range: '100-125', unit: 'mg/dL' },
        { ageGroup: 'Diabetes', ageMin: 18, gender: 'all', range: '≥126', unit: 'mg/dL' },
      ],
    },
    {
      code: 'RBS',
      name: 'Random Blood Sugar',
      category: 'chemistry',
      price: 100,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'mg/dL',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 18, gender: 'all', range: '<140', unit: 'mg/dL', criticalLow: '50', criticalHigh: '500' },
        { ageGroup: 'Prediabetes', ageMin: 18, gender: 'all', range: '140-199', unit: 'mg/dL' },
        { ageGroup: 'Diabetes', ageMin: 18, gender: 'all', range: '≥200', unit: 'mg/dL' },
      ],
    },
    {
      code: 'HBA1C',
      name: 'Glycated Hemoglobin',
      category: 'chemistry',
      price: 300,
      sampleType: 'blood',
      turnaroundTime: 180,
      isActive: true,
      unit: '%',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 18, gender: 'all', range: '<5.7', unit: '%' },
        { ageGroup: 'Prediabetes', ageMin: 18, gender: 'all', range: '5.7-6.4', unit: '%' },
        { ageGroup: 'Diabetes', ageMin: 18, gender: 'all', range: '≥6.5', unit: '%' },
      ],
    },
    {
      code: 'LFT',
      name: 'Liver Function Test',
      category: 'chemistry',
      price: 500,
      sampleType: 'blood',
      turnaroundTime: 180,
      isActive: true,
      description: 'Complete liver function panel',
    },
    {
      code: 'RFT',
      name: 'Renal Function Test',
      category: 'chemistry',
      price: 400,
      sampleType: 'blood',
      turnaroundTime: 180,
      isActive: true,
      description: 'Complete kidney function panel',
    },
    {
      code: 'LIPID',
      name: 'Lipid Profile',
      category: 'chemistry',
      price: 500,
      sampleType: 'blood',
      turnaroundTime: 180,
      isActive: true,
      description: 'Complete lipid panel',
    },

    // ==================== ELECTROLYTES (CBS-50) ====================
    {
      code: 'NA',
      name: 'Sodium',
      category: 'chemistry',
      price: 150,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mmol/L',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '136-145', unit: 'mmol/L', criticalLow: '120', criticalHigh: '160' },
      ],
    },
    {
      code: 'K',
      name: 'Potassium',
      category: 'chemistry',
      price: 150,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mmol/L',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '3.5-5.1', unit: 'mmol/L', criticalLow: '2.5', criticalHigh: '6.5' },
      ],
    },
    {
      code: 'CL',
      name: 'Chloride',
      category: 'chemistry',
      price: 150,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mmol/L',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '98-107', unit: 'mmol/L', criticalLow: '80', criticalHigh: '115' },
      ],
    },
    {
      code: 'CA',
      name: 'Calcium',
      category: 'chemistry',
      price: 150,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mg/dL',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '8.5-10.5', unit: 'mg/dL', criticalLow: '7.0', criticalHigh: '13.0' },
      ],
    },
    {
      code: 'HCO3',
      name: 'Bicarbonate',
      category: 'chemistry',
      price: 150,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      unit: 'mmol/L',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '22-29', unit: 'mmol/L', criticalLow: '15', criticalHigh: '40' },
      ],
    },
    {
      code: 'ELEC',
      name: 'Electrolyte Panel',
      category: 'chemistry',
      price: 400,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      description: 'Complete electrolyte panel',
    },

    // ==================== POCT TESTS (WONDFO FINECARE FIA) ====================
    {
      code: 'CRP',
      name: 'C-Reactive Protein',
      category: 'immunoassay',
      price: 300,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'mg/L',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: '<5.0', unit: 'mg/L' },
        { ageGroup: 'Mild Inflammation', ageMin: 0, gender: 'all', range: '5.0-10.0', unit: 'mg/L' },
        { ageGroup: 'Moderate Inflammation', ageMin: 0, gender: 'all', range: '10.0-50.0', unit: 'mg/L' },
        { ageGroup: 'Severe Inflammation', ageMin: 0, gender: 'all', range: '>50.0', unit: 'mg/L' },
      ],
    },
    {
      code: 'HSCR',
      name: 'High Sensitivity CRP',
      category: 'immunoassay',
      price: 350,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'mg/L',
      referenceRanges: [
        { ageGroup: 'Low CV Risk', ageMin: 18, gender: 'all', range: '<1.0', unit: 'mg/L' },
        { ageGroup: 'Average CV Risk', ageMin: 18, gender: 'all', range: '1.0-3.0', unit: 'mg/L' },
        { ageGroup: 'High CV Risk', ageMin: 18, gender: 'all', range: '>3.0', unit: 'mg/L' },
      ],
    },
    {
      code: 'PCT',
      name: 'Procalcitonin',
      category: 'immunoassay',
      price: 500,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'ng/mL',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: '<0.5', unit: 'ng/mL' },
        { ageGroup: 'Possible Bacterial Infection', ageMin: 0, gender: 'all', range: '0.5-2.0', unit: 'ng/mL' },
        { ageGroup: 'Sepsis Likely', ageMin: 0, gender: 'all', range: '>2.0', unit: 'ng/mL', criticalHigh: '2.0' },
      ],
    },
    {
      code: 'TROP',
      name: 'Troponin I',
      category: 'immunoassay',
      price: 600,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'ng/mL',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: '<0.04', unit: 'ng/mL', criticalHigh: '0.4' },
        { ageGroup: 'Elevated', ageMin: 0, gender: 'all', range: '0.04-0.4', unit: 'ng/mL' },
        { ageGroup: 'MI Likely', ageMin: 0, gender: 'all', range: '>0.4', unit: 'ng/mL' },
      ],
    },
    {
      code: 'BNP',
      name: 'B-Type Natriuretic Peptide',
      category: 'immunoassay',
      price: 700,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'pg/mL',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: '<100', unit: 'pg/mL' },
        { ageGroup: 'Heart Failure Possible', ageMin: 0, gender: 'all', range: '100-400', unit: 'pg/mL' },
        { ageGroup: 'Heart Failure Likely', ageMin: 0, gender: 'all', range: '>400', unit: 'pg/mL', criticalHigh: '400' },
      ],
    },
    {
      code: 'NTPRO',
      name: 'NT-proBNP',
      category: 'immunoassay',
      price: 700,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'pg/mL',
      referenceRanges: [
        { ageGroup: '<50 years', ageMin: 0, ageMax: 50, gender: 'all', range: '<125', unit: 'pg/mL', criticalHigh: '450' },
        { ageGroup: '50-75 years', ageMin: 50, ageMax: 75, gender: 'all', range: '<125', unit: 'pg/mL', criticalHigh: '900' },
        { ageGroup: '>75 years', ageMin: 75, gender: 'all', range: '<125', unit: 'pg/mL', criticalHigh: '1800' },
      ],
    },
    {
      code: 'TSH',
      name: 'Thyroid Stimulating Hormone',
      category: 'immunoassay',
      price: 400,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'µIU/mL',
      referenceRanges: [
        { ageGroup: 'Adult', ageMin: 18, ageMax: 65, gender: 'all', range: '0.5-4.0', unit: 'µIU/mL' },
        { ageGroup: 'Pregnancy (1st trimester)', ageMin: 18, ageMax: 45, gender: 'F', pregnancy: true, condition: '1st trimester', range: '0.1-2.5', unit: 'µIU/mL' },
        { ageGroup: 'Pregnancy (2nd trimester)', ageMin: 18, ageMax: 45, gender: 'F', pregnancy: true, condition: '2nd trimester', range: '0.2-3.0', unit: 'µIU/mL' },
        { ageGroup: 'Pregnancy (3rd trimester)', ageMin: 18, ageMax: 45, gender: 'F', pregnancy: true, condition: '3rd trimester', range: '0.3-3.0', unit: 'µIU/mL' },
      ],
    },
    {
      code: 'FT4',
      name: 'Free T4',
      category: 'immunoassay',
      price: 400,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'ng/dL',
      referenceRanges: [
        { ageGroup: 'Adult', ageMin: 18, gender: 'all', range: '0.8-1.8', unit: 'ng/dL' },
        { ageGroup: 'Pregnancy', ageMin: 18, ageMax: 45, gender: 'F', pregnancy: true, range: '0.8-1.5', unit: 'ng/dL' },
      ],
    },
    {
      code: 'FT3',
      name: 'Free T3',
      category: 'immunoassay',
      price: 400,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'pg/mL',
      referenceRanges: [
        { ageGroup: 'All ages', ageMin: 0, gender: 'all', range: '2.3-4.2', unit: 'pg/mL' },
      ],
    },
    {
      code: 'AFP',
      name: 'Alpha-Fetoprotein',
      category: 'immunoassay',
      price: 500,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'ng/mL',
      referenceRanges: [
        { ageGroup: 'Adult', ageMin: 18, gender: 'all', range: '<10', unit: 'ng/mL' },
        { ageGroup: 'Pregnancy', ageMin: 18, ageMax: 45, gender: 'F', pregnancy: true, range: 'Elevated (varies by week)', unit: 'ng/mL' },
      ],
    },
    {
      code: 'PSA',
      name: 'Prostate Specific Antigen',
      category: 'immunoassay',
      price: 500,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'ng/mL',
      referenceRanges: [
        { ageGroup: '40-49 years', ageMin: 40, ageMax: 49, gender: 'M', range: '<2.5', unit: 'ng/mL' },
        { ageGroup: '50-59 years', ageMin: 50, ageMax: 59, gender: 'M', range: '<3.5', unit: 'ng/mL' },
        { ageGroup: '60-69 years', ageMin: 60, ageMax: 69, gender: 'M', range: '<4.5', unit: 'ng/mL' },
        { ageGroup: '70-79 years', ageMin: 70, ageMax: 79, gender: 'M', range: '<6.5', unit: 'ng/mL' },
      ],
    },
    {
      code: 'CEA',
      name: 'Carcinoembryonic Antigen',
      category: 'immunoassay',
      price: 500,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'ng/mL',
      referenceRanges: [
        { ageGroup: 'Non-smoker', ageMin: 18, gender: 'all', range: '<3.0', unit: 'ng/mL' },
        { ageGroup: 'Smoker', ageMin: 18, gender: 'all', range: '<5.0', unit: 'ng/mL' },
      ],
    },
    {
      code: 'ESTRADIOL',
      name: 'Estradiol',
      category: 'immunoassay',
      price: 500,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'pg/mL',
      referenceRanges: [
        { ageGroup: 'Female (Follicular)', ageMin: 18, ageMax: 50, gender: 'F', condition: 'Follicular', range: '20-350', unit: 'pg/mL' },
        { ageGroup: 'Female (Ovulation)', ageMin: 18, ageMax: 50, gender: 'F', condition: 'Ovulation', range: '150-750', unit: 'pg/mL' },
        { ageGroup: 'Female (Luteal)', ageMin: 18, ageMax: 50, gender: 'F', condition: 'Luteal', range: '30-450', unit: 'pg/mL' },
        { ageGroup: 'Female (Postmenopause)', ageMin: 50, gender: 'F', condition: 'Postmenopause', range: '<20', unit: 'pg/mL' },
      ],
    },
    {
      code: 'PROG',
      name: 'Progesterone',
      category: 'immunoassay',
      price: 500,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'ng/mL',
      referenceRanges: [
        { ageGroup: 'Female (Follicular)', ageMin: 18, ageMax: 50, gender: 'F', condition: 'Follicular', range: '<0.5', unit: 'ng/mL' },
        { ageGroup: 'Female (Ovulation)', ageMin: 18, ageMax: 50, gender: 'F', condition: 'Ovulation', range: '<0.5', unit: 'ng/mL' },
        { ageGroup: 'Female (Luteal)', ageMin: 18, ageMax: 50, gender: 'F', condition: 'Luteal', range: '3-25', unit: 'ng/mL' },
        { ageGroup: 'Female (Postmenopause)', ageMin: 50, gender: 'F', condition: 'Postmenopause', range: '<0.4', unit: 'ng/mL' },
      ],
    },
    {
      code: 'LH',
      name: 'Luteinizing Hormone',
      category: 'immunoassay',
      price: 500,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'IU/L',
      referenceRanges: [
        { ageGroup: 'Female (Follicular)', ageMin: 18, ageMax: 50, gender: 'F', condition: 'Follicular', range: '1.4-9.9', unit: 'IU/L' },
        { ageGroup: 'Female (Ovulation)', ageMin: 18, ageMax: 50, gender: 'F', condition: 'Ovulation', range: '6.2-17.2', unit: 'IU/L' },
        { ageGroup: 'Female (Luteal)', ageMin: 18, ageMax: 50, gender: 'F', condition: 'Luteal', range: '1.1-9.2', unit: 'IU/L' },
        { ageGroup: 'Female (Postmenopause)', ageMin: 50, gender: 'F', condition: 'Postmenopause', range: '19.3-100.6', unit: 'IU/L' },
        { ageGroup: 'Male', ageMin: 18, gender: 'M', range: '1.4-15.4', unit: 'IU/L' },
      ],
    },
    {
      code: 'FSH',
      name: 'Follicle Stimulating Hormone',
      category: 'immunoassay',
      price: 500,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'IU/L',
      referenceRanges: [
        { ageGroup: 'Female (Follicular)', ageMin: 18, ageMax: 50, gender: 'F', condition: 'Follicular', range: '1.4-9.9', unit: 'IU/L' },
        { ageGroup: 'Female (Ovulation)', ageMin: 18, ageMax: 50, gender: 'F', condition: 'Ovulation', range: '6.2-17.2', unit: 'IU/L' },
        { ageGroup: 'Female (Luteal)', ageMin: 18, ageMax: 50, gender: 
'F', condition: 'Luteal', range: '1.1-9.2', unit: 'IU/L' },
        { ageGroup: 'Female (Postmenopause)', ageMin: 50, gender: 'F', condition: 'Postmenopause', range: '19.3-100.6', unit: 'IU/L' },
        { ageGroup: 'Male', ageMin: 18, gender: 'M', range: '1.4-15.4', unit: 'IU/L' },
      ],
    },
    {
      code: 'PROLACTIN',
      name: 'Prolactin',
      category: 'immunoassay',
      price: 500,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'ng/mL',
      referenceRanges: [
        { ageGroup: 'Female', ageMin: 18, gender: 'F', range: '3-27', unit: 'ng/mL' },
        { ageGroup: 'Male', ageMin: 18, gender: 'M', range: '3-13', unit: 'ng/mL' },
      ],
    },
    {
      code: 'BHCG',
      name: 'Beta-HCG',
      category: 'immunoassay',
      price: 400,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'mIU/mL',
      referenceRanges: [
        { ageGroup: 'Non-pregnant', ageMin: 18, gender: 'F', range: '<5', unit: 'mIU/mL' },
        { ageGroup: 'Pregnancy (3 weeks)', ageMin: 18, gender: 'F', pregnancy: true, condition: '3 weeks', range: '5-50', unit: 'mIU/mL' },
        { ageGroup: 'Pregnancy (4 weeks)', ageMin: 18, gender: 'F', pregnancy: true, condition: '4 weeks', range: '5-426', unit: 'mIU/mL' },
        { ageGroup: 'Pregnancy (5 weeks)', ageMin: 18, gender: 'F', pregnancy: true, condition: '5 weeks', range: '18-7340', unit: 'mIU/mL' },
        { ageGroup: 'Pregnancy (6 weeks)', ageMin: 18, gender: 'F', pregnancy: true, condition: '6 weeks', range: '1080-56500', unit: 'mIU/mL' },
        { ageGroup: 'Pregnancy (7-8 weeks)', ageMin: 18, gender: 'F', pregnancy: true, condition: '7-8 weeks', range: '7650-229000', unit: 'mIU/mL' },
      ],
    },
    {
      code: 'TESTOSTERONE',
      name: 'Testosterone',
      category: 'immunoassay',
      price: 500,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'ng/dL',
      referenceRanges: [
        { ageGroup: 'Male (20-29 years)', ageMin: 20, ageMax: 29, gender: 'M', range: '400-1080', unit: 'ng/dL' },
        { ageGroup: 'Male (30-39 years)', ageMin: 30, ageMax: 39, gender: 'M', range: '350-890', unit: 'ng/dL' },
        { ageGroup: 'Male (40-49 years)', ageMin: 40, ageMax: 49, gender: 'M', range: '300-750', unit: 'ng/dL' },
        { ageGroup: 'Male (50-59 years)', ageMin: 50, ageMax: 59, gender: 'M', range: '250-650', unit: 'ng/dL' },
        { ageGroup: 'Male (60+ years)', ageMin: 60, gender: 'M', range: '200-550', unit: 'ng/dL' },
      ],
    },
    {
      code: 'VITD',
      name: 'Vitamin D',
      category: 'immunoassay',
      price: 600,
      sampleType: 'blood',
      turnaroundTime: 60,
      isActive: true,
      unit: 'ng/mL',
      referenceRanges: [
        { ageGroup: 'Deficiency', ageMin: 0, gender: 'all', range: '<20', unit: 'ng/mL' },
        { ageGroup: 'Insufficiency', ageMin: 0, gender: 'all', range: '20-30', unit: 'ng/mL' },
        { ageGroup: 'Sufficient', ageMin: 0, gender: 'all', range: '30-100', unit: 'ng/mL' },
        { ageGroup: 'Optimal', ageMin: 0, gender: 'all', range: '40-60', unit: 'ng/mL' },
      ],
    },
    {
      code: 'DDIMER',
      name: 'D-Dimer',
      category: 'immunoassay',
      price: 500,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      unit: 'µg/mL FEU',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: '<0.5', unit: 'µg/mL FEU' },
        { ageGroup: 'Elevated', ageMin: 0, gender: 'all', range: '>0.5', unit: 'µg/mL FEU' },
      ],
    },

    // ==================== MICROBIOLOGY ====================
    {
      code: 'HPYLORI',
      name: 'H. Pylori Stool Antigen',
      category: 'microbiology',
      price: 300,
      sampleType: 'stool',
      turnaroundTime: 60,
      isActive: true,
      description: 'Helicobacter pylori antigen detection',
    },
    {
      code: 'MALARIA',
      name: 'Malaria RDT',
      category: 'microbiology',
      price: 200,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      description: 'Rapid malaria antigen test',
    },
    {
      code: 'HIV',
      name: 'HIV Rapid Test',
      category: 'microbiology',
      price: 500,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      description: 'HIV antibody rapid test',
    },
    {
      code: 'HBSAG',
      name: 'Hepatitis B Surface Antigen',
      category: 'microbiology',
      price: 400,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      description: 'HBsAg rapid test',
    },
    {
      code: 'HCV',
      name: 'Hepatitis C Antibody',
      category: 'microbiology',
      price: 400,
      sampleType: 'blood',
      turnaroundTime: 30,
      isActive: true,
      description: 'HCV antibody rapid test',
    },
    {
      code: 'WIDAL',
      name: 'Widal Test',
      category: 'microbiology',
      price: 300,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      description: 'Typhoid fever antibody test',
    },
    {
      code: 'VDRL',
      name: 'VDRL',
      category: 'microbiology',
      price: 300,
      sampleType: 'blood',
      turnaroundTime: 120,
      isActive: true,
      description: 'Syphilis screening test',
    },

    // ==================== URINALYSIS ====================
    {
      code: 'URINE',
      name: 'Urinalysis',
      category: 'urinalysis',
      price: 150,
      sampleType: 'urine',
      turnaroundTime: 60,
      isActive: true,
      description: 'Complete urine analysis',
    },
    {
      code: 'UPROTEIN',
      name: 'Urine Protein',
      category: 'urinalysis',
      price: 100,
      sampleType: 'urine',
      turnaroundTime: 60,
      isActive: true,
      unit: 'mg/24h',
      referenceRanges: [
        { ageGroup: 'Normal', ageMin: 0, gender: 'all', range: '<150', unit: 'mg/24h' },
        { ageGroup: 'Microalbuminuria', ageMin: 0, gender: 'all', range: '30-300', unit: 'mg/24h' },
        { ageGroup: 'Proteinuria', ageMin: 0, gender: 'all', range: '>300', unit: 'mg/24h' },
      ],
    },
    {
      code: 'PREGNANCY',
      name: 'Pregnancy Test (Urine)',
      category: 'urinalysis',
      price: 100,
      sampleType: 'urine',
      turnaroundTime: 15,
      isActive: true,
      description: 'Urine HCG pregnancy test',
    },
  ];

  // Insert all tests
  console.log(`Inserting ${tests.length} tests into database...`);
  const insertedTests = await testCatalogModel.insertMany(tests);
  console.log(`Successfully inserted ${insertedTests.length} tests`);

  console.log('Test catalog seeding completed successfully!');
  await app.close();
}

seedTestCatalog()
  .then(() => {
    console.log('Seeding process finished');
    process.exit(0);
  })
  .catch((error) => {
    console.error('Error seeding test catalog:', error);
    process.exit(1);
  });
